// Generado desde main.py — no editar a mano
export interface AppItem { name: string; id: string; domain: string; }
export interface AppCategory { category: string; color: string; apps: AppItem[]; }

export const APP_CATALOG: AppCategory[] = [
  {
    category: "Navegadores Web",
    color: "#42A5F5",
    apps: [
      { name: "Google Chrome", id: "Google.Chrome", domain: "google.com" },
      { name: "Mozilla Firefox", id: "Mozilla.Firefox", domain: "mozilla.org" },
      { name: "Opera", id: "Opera.Opera", domain: "opera.com" },
      { name: "Brave", id: "Brave.Brave", domain: "brave.com" },
      { name: "Vivaldi", id: "Vivaldi.Vivaldi", domain: "vivaldi.com" },
      { name: "Microsoft Edge", id: "Microsoft.Edge", domain: "microsoft.com" },
    ],
  },
  {
    category: "Mensajería",
    color: "#7E57C2",
    apps: [
      { name: "Discord", id: "Discord.Discord", domain: "discord.com" },
      { name: "Zoom", id: "Zoom.Zoom", domain: "zoom.us" },
      { name: "Microsoft Teams", id: "Microsoft.Teams", domain: "microsoft.com" },
      { name: "Telegram", id: "Telegram.TelegramDesktop", domain: "telegram.org" },
      { name: "WhatsApp", id: "WhatsApp.WhatsApp", domain: "whatsapp.com" },
      { name: "Thunderbird", id: "Mozilla.Thunderbird", domain: "thunderbird.net" },
      { name: "Pidgin", id: "Pidgin.Pidgin", domain: "pidgin.im" },
      { name: "Trillian", id: "Cerulean.Trillian", domain: "trillian.im" },
    ],
  },
  {
    category: "Multimedia",
    color: "#EF5350",
    apps: [
      { name: "VLC", id: "VideoLAN.VLC", domain: "videolan.org" },
      { name: "Spotify", id: "Spotify.Spotify", domain: "spotify.com" },
      { name: "foobar2000", id: "PeterPawlowski.foobar2000", domain: "foobar2000.org" },
      { name: "AIMP", id: "AIMP.AIMP", domain: "aimp.ru" },
      { name: "MusicBee", id: "MusicBee.MusicBee", domain: "getmusicbee.com" },
      { name: "Audacity", id: "Audacity.Audacity", domain: "audacityteam.org" },
      { name: "K-Lite Codecs", id: "CodecGuide.K-LiteCodecPack.Standard", domain: "codecguide.com" },
      { name: "GOM Player", id: "GOM.GOMPlayer", domain: "gomlab.com" },
      { name: "HandBrake", id: "HandBrake.HandBrake", domain: "handbrake.fr" },
      { name: "MediaMonkey", id: "MediaMonkey.MediaMonkey", domain: "mediamonkey.com" },
      { name: "iTunes", id: "Apple.iTunes", domain: "apple.com" },
      { name: "Winamp", id: "Nullsoft.Winamp", domain: "winamp.com" },
    ],
  },
  {
    category: "Imagen y Diseño",
    color: "#FF7043",
    apps: [
      { name: "GIMP", id: "GIMP.GIMP", domain: "gimp.org" },
      { name: "Krita", id: "KDE.Krita", domain: "krita.org" },
      { name: "Blender", id: "BlenderFoundation.Blender", domain: "blender.org" },
      { name: "Paint.NET", id: "dotPDN.PaintDotNet", domain: "getpaint.net" },
      { name: "Inkscape", id: "Inkscape.Inkscape", domain: "inkscape.org" },
      { name: "IrfanView", id: "IrfanSkiljan.IrfanView", domain: "irfanview.com" },
      { name: "XnView", id: "XnSoft.XnView", domain: "xnview.com" },
      { name: "FastStone", id: "FastStone.Viewer", domain: "faststone.org" },
      { name: "Greenshot", id: "Greenshot.Greenshot", domain: "getgreenshot.org" },
      { name: "ShareX", id: "ShareX.ShareX", domain: "getsharex.com" },
    ],
  },
  {
    category: "Documentos y Oficina",
    color: "#26A69A",
    apps: [
      { name: "LibreOffice", id: "TheDocumentFoundation.LibreOffice", domain: "libreoffice.org" },
      { name: "OpenOffice", id: "Apache.OpenOffice", domain: "openoffice.org" },
      { name: "Foxit Reader", id: "Foxit.FoxitReader", domain: "foxit.com" },
      { name: "SumatraPDF", id: "SumatraPDF.SumatraPDF", domain: "sumatrapdfreader.org" },
      { name: "Evernote", id: "Evernote.Evernote", domain: "evernote.com" },
      { name: "Obsidian", id: "Obsidian.Obsidian", domain: "obsidian.md" },
      { name: "Notion", id: "Notion.Notion", domain: "notion.so" },
      { name: "Notepad++", id: "Notepad++.Notepad++", domain: "notepad-plus-plus.org" },
    ],
  },
  {
    category: "Seguridad",
    color: "#EC407A",
    apps: [
      { name: "Malwarebytes", id: "Malwarebytes.Malwarebytes", domain: "malwarebytes.com" },
      { name: "Avast", id: "AVAST.AvastFreeAntivirus", domain: "avast.com" },
      { name: "AVG", id: "AVG.AVGAntivirusFree", domain: "avg.com" },
      { name: "Avira", id: "Avira.AviraSecurity", domain: "avira.com" },
      { name: "KeePass 2", id: "DominikReichl.KeePass", domain: "keepass.info" },
      { name: "Bitwarden", id: "Bitwarden.Bitwarden", domain: "bitwarden.com" },
    ],
  },
  {
    category: "Compresión",
    color: "#FFA726",
    apps: [
      { name: "7-Zip", id: "7zip.7zip", domain: "7-zip.org" },
      { name: "WinRAR", id: "RARLab.WinRAR", domain: "rarlab.com" },
      { name: "PeaZip", id: "Giorgiotani.Peazip", domain: "peazip.github.io" },
    ],
  },
  {
    category: "Almacenamiento Cloud",
    color: "#29B6F6",
    apps: [
      { name: "Dropbox", id: "Dropbox.Dropbox", domain: "dropbox.com" },
      { name: "Google Drive", id: "Google.GoogleDrive", domain: "drive.google.com" },
    ],
  },
  {
    category: "Gaming",
    color: "#66BB6A",
    apps: [
      { name: "Steam", id: "Valve.Steam", domain: "steampowered.com" },
      { name: "Epic Games", id: "EpicGames.EpicGamesLauncher", domain: "epicgames.com" },
      { name: "GOG Galaxy", id: "GOG.Galaxy", domain: "gog.com" },
      { name: "EA App", id: "ElectronicArts.EADesktop", domain: "ea.com" },
      { name: "Ubisoft Connect", id: "Ubisoft.Connect", domain: "ubisoft.com" },
      { name: "Battle.net", id: "Blizzard.BattleNet", domain: "blizzard.com" },
    ],
  },
  {
    category: "Utilidades",
    color: "#78909C",
    apps: [
      { name: "Everything", id: "voidtools.Everything", domain: "voidtools.com" },
      { name: "WinDirStat", id: "WinDirStat.WinDirStat", domain: "windirstat.net" },
      { name: "WizTree", id: "AntibodySoftware.WizTree", domain: "diskanalyzer.com" },
      { name: "CCleaner", id: "Piriform.CCleaner", domain: "ccleaner.com" },
      { name: "Revo Uninstaller", id: "RevoUninstaller.RevoUninstaller", domain: "revouninstaller.com" },
      { name: "TeraCopy", id: "CodeSector.TeraCopy", domain: "codesector.com" },
      { name: "TeamViewer", id: "TeamViewer.TeamViewer", domain: "teamviewer.com" },
      { name: "AnyDesk", id: "AnyDeskSoftwareGmbH.AnyDesk", domain: "anydesk.com" },
      { name: "Glary Utilities", id: "Glarysoft.GlaryUtilities", domain: "glarysoft.com" },
      { name: "qBittorrent", id: "qBittorrent.qBittorrent", domain: "qbittorrent.org" },
      { name: "ImgBurn", id: "CDCO.ImgBurn", domain: "imgburn.com" },
      { name: "CDBurnerXP", id: "Canneverbe.CDBurnerXP", domain: "cdburnerxp.se" },
      { name: "Open-Shell", id: "Open-Shell.Open-Shell-Menu", domain: "open-shell.github.io" },
      { name: "Google Earth", id: "Google.GoogleEarth", domain: "earth.google.com" },
      { name: "NV Access (NVDA)", id: "NVAccess.NVDA", domain: "nvaccess.org" },
    ],
  },
  {
    category: "Desarrollo",
    color: "#FFCA28",
    apps: [
      { name: "Visual Studio Code", id: "Microsoft.VisualStudioCode", domain: "code.visualstudio.com" },
      { name: "Cursor", id: "Anysphere.Cursor", domain: "cursor.sh" },
      { name: "Git", id: "Git.Git", domain: "git-scm.com" },
      { name: "Python 3", id: "Python.Python.3", domain: "python.org" },
      { name: "PuTTY", id: "PuTTY.PuTTY", domain: "putty.org" },
      { name: "FileZilla", id: "TimKosse.FileZilla.Client", domain: "filezilla-project.org" },
      { name: "WinSCP", id: "WinSCP.WinSCP", domain: "winscp.net" },
      { name: "WinMerge", id: "WinMerge.WinMerge", domain: "winmerge.org" },
      { name: "Eclipse", id: "EclipseFoundation.EclipseIDE", domain: "eclipse.org" },
    ],
  },
  {
    category: "Runtimes y Redistributables",
    color: "#BDBDBD",
    apps: [
      { name: ".NET Runtime 8 (x64)", id: "Microsoft.DotNet.DesktopRuntime.8", domain: "dotnet.microsoft.com" },
      { name: ".NET Runtime 9 (x64)", id: "Microsoft.DotNet.DesktopRuntime.9", domain: "dotnet.microsoft.com" },
      { name: "VC++ 2015-2022 x64", id: "Microsoft.VCRedist.2015+.x64", domain: "microsoft.com" },
      { name: "VC++ 2015-2022 x86", id: "Microsoft.VCRedist.2015+.x86", domain: "microsoft.com" },
      { name: "VC++ 2013 x64", id: "Microsoft.VCRedist.2013.x64", domain: "microsoft.com" },
      { name: "VC++ 2013 x86", id: "Microsoft.VCRedist.2013.x86", domain: "microsoft.com" },
      { name: "DirectX", id: "Microsoft.DirectX", domain: "microsoft.com" },
      { name: "Java 8  (Temurin)", id: "EclipseAdoptium.Temurin.8.JRE", domain: "adoptium.net" },
      { name: "Java 11 (Temurin)", id: "EclipseAdoptium.Temurin.11.JRE", domain: "adoptium.net" },
      { name: "Java 17 (Temurin)", id: "EclipseAdoptium.Temurin.17.JRE", domain: "adoptium.net" },
      { name: "Java 21 (Temurin)", id: "EclipseAdoptium.Temurin.21.JRE", domain: "adoptium.net" },
    ],
  },
];
