// Traduções em português (pt-BR) do catálogo de Otimizações. Mesmas chaves que
// catalogEn.ts: id da categoria e NOME em espanhol do tweak. Se faltar, cai no inglês.

export const CATEGORY_PT: Record<string, string> = {
  gaming: "Desempenho em Jogos",
  network: "Rede — Menos Latência",
  debloat: "Remover Bloatware",
  privacy: "Privacidade e Telemetria",
  visual: "Desempenho Visual",
  desktop: "Área de Trabalho e Aparência",
  permisos: "Permissões dos Apps",
  services: "Serviços Desnecessários",
  winutil: "Mais Tweaks · WinUtil",
};

export const TWEAK_PT: Record<string, string> = {
  // Gaming
  "Plan de energía: Máximo rendimiento": "Plano de energia: Desempenho máximo",
  "Habilitar Game Mode de Windows": "Ativar o Modo de Jogo do Windows",
  "Deshabilitar Xbox Game Bar y DVR": "Desativar Xbox Game Bar e DVR",
  "Hardware Accelerated GPU Scheduling (HAGS)": "Agendamento de GPU acelerado por hardware (HAGS)",
  "Prioridad CPU máxima para juegos": "Prioridade máxima de CPU para jogos",
  "Deshabilitar Full-Screen Optimization (FSO)": "Desativar Otimizações de Tela Cheia (FSO)",
  "Deshabilitar aceleración del mouse": "Desativar aceleração do mouse",
  "Timer Resolution — 1ms (reduce micro-stutters)": "Timer Resolution — 1ms (reduz micro-travadas)",
  "Core Parking OFF — todos los núcleos activos": "Core Parking OFF — todos os núcleos ativos",
  "Desactivar HPET (timer de alta precisión)": "Desativar HPET (timer de alta precisão)",
  "MSI mode en la GPU (menos latencia)": "Modo MSI na GPU (menos latência)",
  // Red
  "Deshabilitar algoritmo de Nagle (ping más bajo)": "Desativar algoritmo de Nagle (ping mais baixo)",
  "Deshabilitar Teredo": "Desativar Teredo",
  "Optimizar TCP": "Otimizar TCP",
  "Deshabilitar Large Send Offload (LSO)": "Desativar Large Send Offload (LSO)",
  "Reservar 0% de ancho de banda para QoS": "Reservar 0% da largura de banda para QoS",
  // Bloatware
  "Eliminar bloatware (lista completa)": "Eliminar bloatware (lista completa)",
  "Eliminar apps Microsoft innecesarias": "Remover apps desnecessários da Microsoft",
  "Eliminar apps de terceros preinstaladas": "Remover apps pré-instalados de terceiros",
  "Deshabilitar OneDrive": "Desativar OneDrive",
  // Privacidad
  "Deshabilitar telemetría de Windows": "Desativar telemetria do Windows",
  "Deshabilitar tareas programadas de telemetría": "Desativar tarefas agendadas de telemetria",
  "Deshabilitar ID publicitario y Cortana": "Desativar ID de publicidade e Cortana",
  "Deshabilitar Activity History y Timeline": "Desativar Histórico de Atividades e Linha do Tempo",
  "Bloquear telemetría (archivo hosts)": "Bloquear telemetria (arquivo hosts)",
  "Desactivar Recall (captura de IA)": "Desativar Recall (captura por IA)",
  // Visual
  "Desactivar animaciones y efectos visuales": "Desativar animações e efeitos visuais",
  "Deshabilitar transparencia de Windows": "Desativar transparência do Windows",
  "Reducir delay del menú contextual": "Reduzir o atraso do menu de contexto",
  // Escritorio
  "Activar Modo Oscuro (apps y sistema)": "Ativar Modo Escuro (apps e sistema)",
  "Simplificar barra de tareas (conservar buscador)": "Simplificar a barra de tarefas (manter a pesquisa)",
  "Desanclar todas las apps del menu Inicio": "Desafixar todos os apps do menu Iniciar",
  "Desactivar panel de Widgets": "Desativar o painel de Widgets",
  "Desactivar botón Chat / Teams en barra de tareas": "Desativar botão Chat / Teams na barra de tarefas",
  "Desactivar Copilot": "Desativar Copilot",
  "Borrar accesos directos rotos (destino inexistente)": "Apagar atalhos quebrados (destino inexistente)",
  "Quitar OneDrive por completo": "Remover o OneDrive por completo",
  // Permisos
  "Deshabilitar permisos (excepto Cámara, Micrófono, Vídeos)": "Desativar permissões (exceto Câmera, Microfone, Vídeos)",
  "Deshabilitar Activación por Voz": "Desativar Ativação por Voz",
  "Deshabilitar apps en segundo plano": "Desativar apps em segundo plano",
  "Deshabilitar notificaciones de apps": "Desativar notificações de apps",
  // Servicios
  "Deshabilitar SysMain / Superfetch": "Desativar SysMain / Superfetch",
  "Deshabilitar Windows Search (indexado)": "Desativar Windows Search (indexação)",
  "Deshabilitar servicios de Xbox": "Desativar serviços do Xbox",
  "Deshabilitar Remote Registry": "Desativar Registro Remoto",
  "Deshabilitar Print Spooler (si no usas impresora)": "Desativar Spooler de Impressão (se você não usa impressora)",
  "Deshabilitar Windows Defender (ADVERTENCIA: reduce proteccion)": "Desativar Windows Defender (ATENÇÃO: reduz a proteção)",
  // WinUtil
  "Menú contextual clásico (clic derecho de W10)": "Menu de contexto clássico (clique direito do W10)",
  "Mostrar extensiones de archivo": "Mostrar extensões de arquivo",
  "Mostrar archivos y carpetas ocultos": "Mostrar arquivos e pastas ocultos",
  "“Finalizar tarea” con clic derecho en la barra": "“Finalizar tarefa” com clique direito na barra",
  "Alinear barra de tareas a la izquierda": "Alinhar a barra de tarefas à esquerda",
  "Desactivar Consumer Features (sugerencias y anuncios)": "Desativar Consumer Features (sugestões e anúncios)",
  "Quitar sugerencias/anuncios del menú Inicio": "Remover sugestões/anúncios do menu Iniciar",
  "Quitar búsqueda de Bing del menú Inicio": "Remover a pesquisa do Bing do menu Iniciar",
  "Debloat de Microsoft Edge (quitar promos)": "Debloat do Microsoft Edge (remover promoções)",
  "Desactivar seguimiento de ubicación": "Desativar rastreamento de localização",
  "Desactivar Storage Sense": "Desativar o Sensor de Armazenamento",
  "Desactivar Wi-Fi Sense": "Desativar Wi-Fi Sense",
  "Desactivar telemetría de PowerShell 7": "Desativar telemetria do PowerShell 7",
  "Desactivar hibernación (libera espacio)": "Desativar hibernação (libera espaço)",
  "Desactivar IPv6": "Desativar IPv6",
  "Desactivar reinicio automático tras actualizar": "Desativar reinício automático após atualizar",
  "Pantalla azul (BSOD) con detalles técnicos": "Tela azul (BSOD) com detalhes técnicos",
  "Mensajes detallados al iniciar sesión": "Mensagens detalhadas ao entrar",
  "Activar NumLock al iniciar Windows": "Ativar NumLock ao iniciar o Windows",
  "Desactivar Sticky Keys": "Desativar Teclas de Aderência",
  "Mostrar segundos en el reloj de la barra": "Mostrar segundos no relógio da barra",
  "Hora del sistema en UTC (dual-boot con Linux)": "Hora do sistema em UTC (dual-boot com Linux)",
  "Desactivar servicio HomeGroup": "Desativar o serviço Grupo Doméstico",
  "Desinstalar Microsoft Edge (si usás otro navegador)": "Desinstalar o Microsoft Edge (se você usa outro navegador)",
};

export const TWEAK_DESC_PT: Record<string, string> = {
  "Plan de energía: Máximo rendimiento": "Ativa o plano Desempenho Máximo (ou Alto desempenho se o seu Windows não tiver): a CPU não baixa a frequência para economizar energia, ideal para jogar. Reaproveita o plano se já existir, sem duplicatas.",
  "Habilitar Game Mode de Windows": "Prioriza recursos para o jogo em primeiro plano e reduz tarefas em segundo plano enquanto você joga.",
  "Deshabilitar Xbox Game Bar y DVR": "Desliga a gravação em segundo plano da Game Bar, que usa CPU/GPU e pode causar travadinhas.",
  "Hardware Accelerated GPU Scheduling (HAGS)": "Deixa a GPU gerenciar a própria memória/agendamento, reduzindo a latência em placas modernas.",
  "Prioridad CPU máxima para juegos": "Aumenta a prioridade de CPU/GPU das tarefas de jogo no registro do Windows.",
  "Deshabilitar Full-Screen Optimization (FSO)": "Força a tela cheia exclusiva de verdade, reduzindo o input lag em alguns jogos.",
  "Deshabilitar aceleración del mouse": "Deixa o movimento do mouse 1:1 (sem aceleração), essencial para mirar em shooters.",
  "Timer Resolution — 1ms (reduce micro-stutters)": "Força o timer do sistema a 1ms para suavizar micro-travadas. Avançado: cria uma tarefa na inicialização.",
  "Core Parking OFF — todos los núcleos activos": "Impede que o Windows 'estacione' núcleos da CPU, mantendo todos ativos. Avançado.",
  "MSI mode en la GPU (menos latencia)": "Ativa interrupções por mensagem (MSI) na GPU para reduzir a latência. Avançado: precisa reiniciar.",
  "Deshabilitar algoritmo de Nagle (ping más bajo)": "Desativa o agrupamento de pacotes TCP, baixando a latência em jogos online.",
  "Deshabilitar Teredo": "Desliga o túnel IPv6 Teredo, que pode causar problemas de conexão em alguns jogos.",
  "Optimizar TCP": "Ajusta parâmetros do TCP (autotuning, RSS) para um desempenho de rede melhor.",
  "Deshabilitar Large Send Offload (LSO)": "Desativa o LSO, que causa picos de latência em muitas placas de rede.",
  "Reservar 0% de ancho de banda para QoS": "Libera os 20% da banda que o Windows reserva para QoS por padrão. Avançado.",
  "Deshabilitar telemetría de Windows": "Reduz ao mínimo a coleta de dados de diagnóstico do Windows.",
  "Deshabilitar ID publicitario y Cortana": "Desliga o ID de publicidade e a assistente Cortana.",
  "Bloquear telemetría (archivo hosts)": "Adiciona os domínios de telemetria da Microsoft ao arquivo hosts. ATENÇÃO: o Windows Defender detecta isso como ameaça (HostsFileHijack) e reverte. Não é necessário: \"Desativar telemetria do Windows\" já bloqueia pelo registro.",
  "Desactivar Recall (captura de IA)": "Desativa o Recall do Windows 11, que tira capturas periódicas da sua tela.",
  "Desactivar animaciones y efectos visuales": "Remove as animações de janelas e menus para uma resposta mais ágil.",
  "Deshabilitar transparencia de Windows": "Desliga os efeitos de transparência, economizando um pouco de GPU.",
  "Activar Modo Oscuro (apps y sistema)": "Muda o Windows e os aplicativos para o tema escuro.",
  "Quitar OneDrive por completo": "Desinstala o OneDrive e apaga a pasta dele. Avançado: só faça se você não usa.",
  "Deshabilitar SysMain / Superfetch": "Desliga o serviço de pré-carregamento, útil principalmente em PCs com SSD.",
  "Deshabilitar Windows Search (indexado)": "Desliga a indexação da pesquisa, que usa o disco. Avançado: a pesquisa fica mais lenta.",
  "Eliminar apps Microsoft innecesarias": "Remove apps da Microsoft que quase ninguém usa (Notícias, Clima, Paciência, Mapas, Teams, Outlook novo, Copilot, Clipchamp…) para todos os usuários, e impede que o Windows os reinstale. Nunca mexe em Xbox/Game Pass, na Store nem nos seus jogos.",
  "Eliminar apps de terceros preinstaladas": "Remove jogos e apps de terceiros que o Windows instala como “sugestão” (Candy Crush, TikTok, Facebook, Netflix, Spotify, McAfee…) e impede que voltem. Não mexe em Minecraft, Roblox nem WhatsApp.",
  "Eliminar bloatware (lista completa)": "Tudo dos dois anteriores mais apps do Windows que alguns usam: Widgets, Notas Autoadesivas, Gravador, Assistência Rápida, Reprodutor Multimídia, Paint 3D, Whiteboard… É uma lista fixa: nunca apaga apps que você instalou.",
  "Desinstalar Microsoft Edge (si usás otro navegador)": "Desinstala o Edge com o desinstalador oficial e impede que o Windows o reinstale. Só faz isso se você tiver outro navegador instalado (Chrome, Firefox…). Não mexe no WebView2, que outros apps usam. Desfaça em Reativar → Microsoft Edge.",
  "Desactivar HPET (timer de alta precisión)": "Desativa o temporizador HPET e o “dynamic tick”. Em alguns PCs reduz a latência de entrada; em outros piora. Requer reiniciar. Avançado: teste e reverta se notar travadas.",
  "Deshabilitar OneDrive": "Desinstala o OneDrive e impede que volte a sincronizar. Os arquivos da pasta OneDrive não são apagados. Faça só se não usa o OneDrive.",
  "Deshabilitar tareas programadas de telemetría": "Desliga as tarefas que enviam dados de uso à Microsoft (Experiência do Cliente, Compatibilidade, Diagnóstico de disco…). Não afeta o funcionamento do Windows.",
  "Deshabilitar Activity History y Timeline": "O Windows para de salvar e enviar seu histórico de atividades (quais apps e arquivos você abre).",
  "Reducir delay del menú contextual": "Os menus abrem na hora em vez de esperar ~0,4 s ao passar o mouse.",
  "Simplificar barra de tareas (conservar buscador)": "Remove da barra os botões de Visão de Tarefas, Cortana e Pessoas. A pesquisa continua.",
  "Desanclar todas las apps del menu Inicio": "Deixa o menu Iniciar sem apps fixados (para montar do seu jeito). Avançado: você vai precisar fixar de novo os que usa.",
  "Desactivar panel de Widgets": "Remove o botão de Widgets (notícias, clima) da barra e o bloqueia. Economiza memória e processos em segundo plano.",
  "Desactivar botón Chat / Teams en barra de tareas": "Remove o botão de Chat/Teams da barra de tarefas do Windows 11.",
  "Desactivar Copilot": "Remove o botão do Copilot e o desativa por política.",
  "Borrar accesos directos rotos (destino inexistente)": "Apaga da área de trabalho e do menu Iniciar os atalhos que apontam para programas que não existem mais.",
  "Deshabilitar permisos (excepto Cámara, Micrófono, Vídeos)": "Remove dos apps o acesso a localização, contatos, calendário, arquivos, Bluetooth e mais. Câmera e microfone continuam. Se um app parar de funcionar, use Reativar → Permissões.",
  "Deshabilitar Activación por Voz": "Os apps (como a Cortana) param de escutar uma palavra de ativação em segundo plano.",
  "Deshabilitar apps en segundo plano": "Os apps da Store não rodam quando você não usa: menos RAM e CPU. Atenção: apps da Store (WhatsApp, Spotify…) podem parar de mostrar notificações.",
  "Deshabilitar notificaciones de apps": "Bloqueia as notificações dos apps. Menos interrupções jogando, mas você não verá avisos de nenhum app.",
  "Deshabilitar servicios de Xbox": "Desliga os serviços do Xbox. Avançado: quebra o Game Pass para PC (login), os saves na nuvem e os controles/acessórios Xbox. Só se não usa nada do Xbox. Desfaça em Reativar → Xbox / Game Pass.",
  "Deshabilitar Remote Registry": "Impede que outros PCs da rede leiam ou mudem seu registro. Mais seguro; quase ninguém precisa.",
  "Deshabilitar Print Spooler (si no usas impresora)": "Desliga o serviço de impressão. Avançado: você não poderá imprimir nem usar “Imprimir em PDF” até reativar (Reativar → Impressora).",
  "Deshabilitar Windows Defender (ADVERTENCIA: reduce proteccion)": "Desliga o antivírus do Windows. Perigoso: seu PC fica sem proteção se você não tiver outro antivírus. No Windows moderno a “Proteção contra Adulterações” costuma bloquear: o app avisa se não conseguiu.",
  "Menú contextual clásico (clic derecho de W10)": "Volta ao menu completo de clique direito do Windows 10, sem o “Mostrar mais opções”. Reinicia o Explorer.",
  "Mostrar extensiones de archivo": "Mostra a extensão (.exe, .pdf, .jpg…). Ajuda a detectar arquivos perigosos disfarçados (ex. “foto.jpg.exe”).",
  "Mostrar archivos y carpetas ocultos": "Mostra no Explorer os arquivos e pastas ocultos (como AppData).",
  "“Finalizar tarea” con clic derecho en la barra": "Adiciona “Finalizar tarefa” ao clique direito de cada app na barra: feche um jogo travado sem abrir o Gerenciador de Tarefas.",
  "Alinear barra de tareas a la izquierda": "Coloca o botão Iniciar e os ícones à esquerda, como no Windows 10.",
  "Desactivar Consumer Features (sugerencias y anuncios)": "Impede que o Windows instale sozinho apps “sugeridos” (Candy Crush e cia.) e mostre promoções.",
  "Quitar sugerencias/anuncios del menú Inicio": "Remove os apps recomendados e os anúncios do menu Iniciar.",
  "Quitar búsqueda de Bing del menú Inicio": "A pesquisa do Iniciar só procura no seu PC: mais rápida e sem resultados web do Bing.",
  "Debloat de Microsoft Edge (quitar promos)": "Desliga no Edge o assistente de compras, a barra lateral e as recomendações. Não desinstala o Edge.",
  "Desactivar seguimiento de ubicación": "Desliga o serviço de localização do Windows. Apps de mapas ou clima não saberão onde você está.",
  "Desactivar Storage Sense": "Impede que o Windows apague sozinho arquivos temporários ou da Lixeira. Útil se você prefere limpar manualmente.",
  "Desactivar Wi-Fi Sense": "Impede que o Windows compartilhe ou se conecte sozinho a redes Wi-Fi sugeridas.",
  "Desactivar telemetría de PowerShell 7": "O PowerShell 7 para de enviar dados de uso à Microsoft. Não afeta o Windows PowerShell.",
  "Desactivar hibernación (libera espacio)": "Apaga o arquivo de hibernação (vários GB). Avançado: também desativa a “inicialização rápida” e a opção Hibernar.",
  "Desactivar IPv6": "Desativa o IPv6 nos seus adaptadores de rede. Avançado: alguns provedores e jogos usam; se perder a conexão, reverta.",
  "Desactivar reinicio automático tras actualizar": "O Windows Update não reinicia o PC sozinho enquanto alguém estiver conectado (não corta sua partida).",
  "Pantalla azul (BSOD) con detalles técnicos": "Se aparecer uma tela azul, mostra o código e o driver que a causou: ajuda a achar o problema.",
  "Mensajes detallados al iniciar sesión": "Mostra o que o Windows está fazendo ao iniciar e desligar (útil se demora muito).",
  "Activar NumLock al iniciar Windows": "O teclado numérico fica ativado desde a tela de login.",
  "Desactivar Sticky Keys": "Evita o aviso de “Teclas de Aderência” ao apertar Shift 5 vezes (muito chato em jogos).",
  "Mostrar segundos en el reloj de la barra": "O relógio da barra de tarefas mostra também os segundos.",
  "Hora del sistema en UTC (dual-boot con Linux)": "Faz o Windows interpretar o relógio do PC em UTC, como o Linux. Avançado: só se usa Linux no mesmo PC e a hora fica errada.",
  "Desactivar servicio HomeGroup": "Desliga os serviços de Grupo Doméstico (recurso antigo de rede que o Windows 10/11 não usa mais).",
};
