// Traducciones al inglés del catálogo de Optimizaciones. Las claves son el id de la
// categoría y el NOMBRE en español del tweak (que es su identificador en catalog.ts,
// extraCatalog.ts y tweakDesc.ts). Si falta una entrada se muestra el español.

export const CATEGORY_EN: Record<string, string> = {
  gaming: "Gaming Performance",
  network: "Network — Lower Latency",
  debloat: "Remove Bloatware",
  privacy: "Privacy & Telemetry",
  visual: "Visual Performance",
  desktop: "Desktop & Appearance",
  permisos: "App Permissions",
  services: "Unneeded Services",
  winutil: "More Tweaks · WinUtil",
};

export const TWEAK_EN: Record<string, string> = {
  // Gaming
  "Plan de energía: Máximo rendimiento": "Power plan: Maximum performance",
  "Habilitar Game Mode de Windows": "Enable Windows Game Mode",
  "Deshabilitar Xbox Game Bar y DVR": "Disable Xbox Game Bar and DVR",
  "Hardware Accelerated GPU Scheduling (HAGS)": "Hardware Accelerated GPU Scheduling (HAGS)",
  "Prioridad CPU máxima para juegos": "Maximum CPU priority for games",
  "Deshabilitar Full-Screen Optimization (FSO)": "Disable Full-Screen Optimization (FSO)",
  "Deshabilitar aceleración del mouse": "Disable mouse acceleration",
  "Timer Resolution — 1ms (reduce micro-stutters)": "Timer Resolution — 1ms (reduces micro-stutters)",
  "Core Parking OFF — todos los núcleos activos": "Core Parking OFF — all cores active",
  "Desactivar HPET (timer de alta precisión)": "Disable HPET (high precision event timer)",
  "MSI mode en la GPU (menos latencia)": "MSI mode on the GPU (lower latency)",
  // Red
  "Deshabilitar algoritmo de Nagle (ping más bajo)": "Disable Nagle's algorithm (lower ping)",
  "Deshabilitar Teredo": "Disable Teredo",
  "Optimizar TCP": "Optimize TCP",
  "Deshabilitar Large Send Offload (LSO)": "Disable Large Send Offload (LSO)",
  "Reservar 0% de ancho de banda para QoS": "Reserve 0% bandwidth for QoS",
  // Bloatware
  "[Sycnex] Remove ALL Bloatware (lista completa)": "[Sycnex] Remove ALL Bloatware (full list)",
  "Eliminar apps Microsoft innecesarias": "Remove unneeded Microsoft apps",
  "Eliminar apps de terceros preinstaladas": "Remove preinstalled third-party apps",
  "Deshabilitar OneDrive": "Disable OneDrive",
  // Privacidad
  "Deshabilitar telemetría de Windows": "Disable Windows telemetry",
  "Deshabilitar tareas programadas de telemetría": "Disable telemetry scheduled tasks",
  "Deshabilitar ID publicitario y Cortana": "Disable advertising ID and Cortana",
  "Deshabilitar Activity History y Timeline": "Disable Activity History and Timeline",
  "Bloquear telemetría (archivo hosts)": "Block telemetry (hosts file)",
  "Desactivar Recall (captura de IA)": "Disable Recall (AI screen capture)",
  // Visual
  "Desactivar animaciones y efectos visuales": "Disable animations and visual effects",
  "Deshabilitar transparencia de Windows": "Disable Windows transparency",
  "Reducir delay del menú contextual": "Reduce context menu delay",
  // Escritorio
  "Activar Modo Oscuro (apps y sistema)": "Enable Dark Mode (apps and system)",
  "Simplificar barra de tareas (conservar buscador)": "Simplify taskbar (keep search)",
  "Desanclar todas las apps del menu Inicio": "Unpin all apps from the Start menu",
  "Desactivar panel de Widgets": "Disable Widgets panel",
  "Desactivar botón Chat / Teams en barra de tareas": "Disable Chat / Teams button on taskbar",
  "Desactivar Copilot": "Disable Copilot",
  "Borrar accesos directos rotos (destino inexistente)": "Delete broken shortcuts (missing target)",
  "Quitar OneDrive por completo": "Remove OneDrive completely",
  // Permisos
  "Deshabilitar permisos (excepto Cámara, Micrófono, Vídeos)": "Disable permissions (except Camera, Microphone, Videos)",
  "Deshabilitar Activación por Voz": "Disable Voice Activation",
  "Deshabilitar apps en segundo plano": "Disable background apps",
  "Deshabilitar notificaciones de apps": "Disable app notifications",
  // Servicios
  "Deshabilitar SysMain / Superfetch": "Disable SysMain / Superfetch",
  "Deshabilitar Windows Search (indexado)": "Disable Windows Search (indexing)",
  "Deshabilitar servicios de Xbox": "Disable Xbox services",
  "Deshabilitar Remote Registry": "Disable Remote Registry",
  "Deshabilitar Print Spooler (si no usas impresora)": "Disable Print Spooler (if you don't use a printer)",
  "Deshabilitar Windows Defender (ADVERTENCIA: reduce proteccion)": "Disable Windows Defender (WARNING: reduces protection)",
  // WinUtil
  "Menú contextual clásico (clic derecho de W10)": "Classic context menu (W10 right-click)",
  "Mostrar extensiones de archivo": "Show file extensions",
  "Mostrar archivos y carpetas ocultos": "Show hidden files and folders",
  "“Finalizar tarea” con clic derecho en la barra": "“End task” on taskbar right-click",
  "Alinear barra de tareas a la izquierda": "Align taskbar to the left",
  "Desactivar Consumer Features (sugerencias y anuncios)": "Disable Consumer Features (suggestions and ads)",
  "Quitar sugerencias/anuncios del menú Inicio": "Remove suggestions/ads from the Start menu",
  "Quitar búsqueda de Bing del menú Inicio": "Remove Bing search from the Start menu",
  "Debloat de Microsoft Edge (quitar promos)": "Debloat Microsoft Edge (remove promos)",
  "Desactivar seguimiento de ubicación": "Disable location tracking",
  "Desactivar Storage Sense": "Disable Storage Sense",
  "Desactivar Wi-Fi Sense": "Disable Wi-Fi Sense",
  "Desactivar telemetría de PowerShell 7": "Disable PowerShell 7 telemetry",
  "Desactivar hibernación (libera espacio)": "Disable hibernation (frees space)",
  "Desactivar IPv6": "Disable IPv6",
  "Desactivar reinicio automático tras actualizar": "Disable automatic restart after updates",
  "Pantalla azul (BSOD) con detalles técnicos": "Blue screen (BSOD) with technical details",
  "Mensajes detallados al iniciar sesión": "Verbose messages at sign-in",
  "Activar NumLock al iniciar Windows": "Turn on NumLock at Windows startup",
  "Desactivar Sticky Keys": "Disable Sticky Keys",
  "Mostrar segundos en el reloj de la barra": "Show seconds on the taskbar clock",
  "Hora del sistema en UTC (dual-boot con Linux)": "System time in UTC (dual-boot with Linux)",
  "Desactivar servicio HomeGroup": "Disable HomeGroup service",
};

export const TWEAK_DESC_EN: Record<string, string> = {
  "Plan de energía: Máximo rendimiento": "Activates the Ultimate Performance plan (or High performance if your Windows doesn't have it): the CPU doesn't lower its frequency to save power, ideal for gaming. Reuses the plan if it already exists, no duplicates.",
  "Habilitar Game Mode de Windows": "Prioritizes resources for the foreground game and reduces background tasks while you play.",
  "Deshabilitar Xbox Game Bar y DVR": "Turns off Game Bar background recording, which uses CPU/GPU and can cause stutter.",
  "Hardware Accelerated GPU Scheduling (HAGS)": "Lets the GPU manage its own memory/scheduling, lowering latency on modern cards.",
  "Prioridad CPU máxima para juegos": "Raises the CPU/GPU priority for game tasks in the Windows registry.",
  "Deshabilitar Full-Screen Optimization (FSO)": "Forces true exclusive fullscreen, reducing input lag in some games.",
  "Deshabilitar aceleración del mouse": "Makes mouse movement 1:1 (no acceleration), key for aiming in shooters.",
  "Timer Resolution — 1ms (reduce micro-stutters)": "Forces the system timer to 1ms to smooth out micro-stutters. Advanced: creates a startup task.",
  "Core Parking OFF — todos los núcleos activos": "Stops Windows from 'parking' CPU cores, keeping them all active. Advanced.",
  "MSI mode en la GPU (menos latencia)": "Enables message-signaled interrupts (MSI) on the GPU to reduce latency. Advanced: requires a restart.",
  "Deshabilitar algoritmo de Nagle (ping más bajo)": "Disables TCP packet batching, lowering latency in online games.",
  "Deshabilitar Teredo": "Turns off the Teredo IPv6 tunnel, which can cause connection issues in some games.",
  "Optimizar TCP": "Tunes TCP parameters (autotuning, RSS) for better network performance.",
  "Deshabilitar Large Send Offload (LSO)": "Disables LSO, which causes latency spikes on many network adapters.",
  "Reservar 0% de ancho de banda para QoS": "Frees the 20% of bandwidth Windows reserves for QoS by default. Advanced.",
  "Deshabilitar telemetría de Windows": "Reduces Windows diagnostic data collection to the minimum.",
  "Deshabilitar ID publicitario y Cortana": "Turns off the advertising ID and the Cortana assistant.",
  "Bloquear telemetría (archivo hosts)": "Adds Microsoft telemetry domains to the hosts file. WARNING: Windows Defender flags this as a threat (HostsFileHijack) and reverts it. Not needed: \"Disable Windows telemetry\" already blocks it via the registry.",
  "Desactivar Recall (captura de IA)": "Disables Windows 11 Recall, which takes periodic screenshots of your screen.",
  "Desactivar animaciones y efectos visuales": "Removes window and menu animations for a snappier response.",
  "Deshabilitar transparencia de Windows": "Turns off transparency effects, saving some GPU.",
  "Activar Modo Oscuro (apps y sistema)": "Switches Windows and apps to the dark theme.",
  "Quitar OneDrive por completo": "Uninstalls OneDrive and deletes its folder. Advanced: only do it if you don't use it.",
  "Deshabilitar SysMain / Superfetch": "Turns off the preload service, mostly useful on PCs with an SSD.",
  "Deshabilitar Windows Search (indexado)": "Turns off search indexing, which uses disk. Advanced: search becomes slower.",
};
