// Traducciones al inglés del catálogo de Optimizaciones. Las claves son el id de la
// categoría y el NOMBRE en español del tweak (que es su identificador en catalog.ts,
// extraCatalog.ts y tweakDesc.ts). Si falta una entrada se muestra el español.

export const CATEGORY_EN: Record<string, string> = {
  gaming: "Gaming Performance",
  network: "Network — Lower Latency",
  debloat: "Remove Bloatware",
  privacy: "Privacy & Telemetry",
  visual: "Visual Performance",
  desktop: "Desktop & Appearance",
  permisos: "App Permissions",
  services: "Unneeded Services",
  winutil: "More Tweaks · WinUtil",
};

export const TWEAK_EN: Record<string, string> = {
  // Gaming
  "Plan de energía: Máximo rendimiento": "Power plan: Maximum performance",
  "Habilitar Game Mode de Windows": "Enable Windows Game Mode",
  "Deshabilitar Xbox Game Bar y DVR": "Disable Xbox Game Bar and DVR",
  "Hardware Accelerated GPU Scheduling (HAGS)": "Hardware Accelerated GPU Scheduling (HAGS)",
  "Prioridad CPU máxima para juegos": "Maximum CPU priority for games",
  "Deshabilitar Full-Screen Optimization (FSO)": "Disable Full-Screen Optimization (FSO)",
  "Deshabilitar aceleración del mouse": "Disable mouse acceleration",
  "Timer Resolution — 1ms (reduce micro-stutters)": "Timer Resolution — 1ms (reduces micro-stutters)",
  "Core Parking OFF — todos los núcleos activos": "Core Parking OFF — all cores active",
  "Desactivar HPET (timer de alta precisión)": "Disable HPET (high precision event timer)",
  "MSI mode en la GPU (menos latencia)": "MSI mode on the GPU (lower latency)",
  // Red
  "Deshabilitar algoritmo de Nagle (ping más bajo)": "Disable Nagle's algorithm (lower ping)",
  "Deshabilitar Teredo": "Disable Teredo",
  "Optimizar TCP": "Optimize TCP",
  "Deshabilitar Large Send Offload (LSO)": "Disable Large Send Offload (LSO)",
  "Reservar 0% de ancho de banda para QoS": "Reserve 0% bandwidth for QoS",
  // Bloatware
  "Eliminar bloatware (lista completa)": "Remove bloatware (full list)",
  "Eliminar apps Microsoft innecesarias": "Remove unneeded Microsoft apps",
  "Eliminar apps de terceros preinstaladas": "Remove preinstalled third-party apps",
  "Deshabilitar OneDrive": "Disable OneDrive",
  // Privacidad
  "Deshabilitar telemetría de Windows": "Disable Windows telemetry",
  "Deshabilitar tareas programadas de telemetría": "Disable telemetry scheduled tasks",
  "Deshabilitar ID publicitario y Cortana": "Disable advertising ID and Cortana",
  "Deshabilitar Activity History y Timeline": "Disable Activity History and Timeline",
  "Bloquear telemetría (archivo hosts)": "Block telemetry (hosts file)",
  "Desactivar Recall (captura de IA)": "Disable Recall (AI screen capture)",
  // Visual
  "Desactivar animaciones y efectos visuales": "Disable animations and visual effects",
  "Deshabilitar transparencia de Windows": "Disable Windows transparency",
  "Reducir delay del menú contextual": "Reduce context menu delay",
  // Escritorio
  "Activar Modo Oscuro (apps y sistema)": "Enable Dark Mode (apps and system)",
  "Simplificar barra de tareas (conservar buscador)": "Simplify taskbar (keep search)",
  "Desanclar todas las apps del menu Inicio": "Unpin all apps from the Start menu",
  "Desactivar panel de Widgets": "Disable Widgets panel",
  "Desactivar botón Chat / Teams en barra de tareas": "Disable Chat / Teams button on taskbar",
  "Desactivar Copilot": "Disable Copilot",
  "Borrar accesos directos rotos (destino inexistente)": "Delete broken shortcuts (missing target)",
  "Quitar OneDrive por completo": "Remove OneDrive completely",
  // Permisos
  "Deshabilitar permisos (excepto Cámara, Micrófono, Vídeos)": "Disable permissions (except Camera, Microphone, Videos)",
  "Deshabilitar Activación por Voz": "Disable Voice Activation",
  "Deshabilitar apps en segundo plano": "Disable background apps",
  "Deshabilitar notificaciones de apps": "Disable app notifications",
  // Servicios
  "Deshabilitar SysMain / Superfetch": "Disable SysMain / Superfetch",
  "Deshabilitar Windows Search (indexado)": "Disable Windows Search (indexing)",
  "Deshabilitar servicios de Xbox": "Disable Xbox services",
  "Deshabilitar Remote Registry": "Disable Remote Registry",
  "Deshabilitar Print Spooler (si no usas impresora)": "Disable Print Spooler (if you don't use a printer)",
  "Deshabilitar Windows Defender (ADVERTENCIA: reduce proteccion)": "Disable Windows Defender (WARNING: reduces protection)",
  // WinUtil
  "Menú contextual clásico (clic derecho de W10)": "Classic context menu (W10 right-click)",
  "Mostrar extensiones de archivo": "Show file extensions",
  "Mostrar archivos y carpetas ocultos": "Show hidden files and folders",
  "“Finalizar tarea” con clic derecho en la barra": "“End task” on taskbar right-click",
  "Alinear barra de tareas a la izquierda": "Align taskbar to the left",
  "Desactivar Consumer Features (sugerencias y anuncios)": "Disable Consumer Features (suggestions and ads)",
  "Quitar sugerencias/anuncios del menú Inicio": "Remove suggestions/ads from the Start menu",
  "Quitar búsqueda de Bing del menú Inicio": "Remove Bing search from the Start menu",
  "Debloat de Microsoft Edge (quitar promos)": "Debloat Microsoft Edge (remove promos)",
  "Desactivar seguimiento de ubicación": "Disable location tracking",
  "Desactivar Storage Sense": "Disable Storage Sense",
  "Desactivar Wi-Fi Sense": "Disable Wi-Fi Sense",
  "Desactivar telemetría de PowerShell 7": "Disable PowerShell 7 telemetry",
  "Desactivar hibernación (libera espacio)": "Disable hibernation (frees space)",
  "Desactivar IPv6": "Disable IPv6",
  "Desactivar reinicio automático tras actualizar": "Disable automatic restart after updates",
  "Pantalla azul (BSOD) con detalles técnicos": "Blue screen (BSOD) with technical details",
  "Mensajes detallados al iniciar sesión": "Verbose messages at sign-in",
  "Activar NumLock al iniciar Windows": "Turn on NumLock at Windows startup",
  "Desactivar Sticky Keys": "Disable Sticky Keys",
  "Mostrar segundos en el reloj de la barra": "Show seconds on the taskbar clock",
  "Hora del sistema en UTC (dual-boot con Linux)": "System time in UTC (dual-boot with Linux)",
  "Desactivar servicio HomeGroup": "Disable HomeGroup service",
  "Desinstalar Microsoft Edge (si usás otro navegador)": "Uninstall Microsoft Edge (if you use another browser)",
};

export const TWEAK_DESC_EN: Record<string, string> = {
  "Plan de energía: Máximo rendimiento": "Activates the Ultimate Performance plan (or High performance if your Windows doesn't have it): the CPU doesn't lower its frequency to save power, ideal for gaming. Reuses the plan if it already exists, no duplicates.",
  "Habilitar Game Mode de Windows": "Prioritizes resources for the foreground game and reduces background tasks while you play.",
  "Deshabilitar Xbox Game Bar y DVR": "Turns off Game Bar background recording, which uses CPU/GPU and can cause stutter.",
  "Hardware Accelerated GPU Scheduling (HAGS)": "Lets the GPU manage its own memory/scheduling, lowering latency on modern cards.",
  "Prioridad CPU máxima para juegos": "Raises the CPU/GPU priority for game tasks in the Windows registry.",
  "Deshabilitar Full-Screen Optimization (FSO)": "Forces true exclusive fullscreen, reducing input lag in some games.",
  "Deshabilitar aceleración del mouse": "Makes mouse movement 1:1 (no acceleration), key for aiming in shooters.",
  "Timer Resolution — 1ms (reduce micro-stutters)": "Forces the system timer to 1ms to smooth out micro-stutters. Advanced: creates a startup task.",
  "Core Parking OFF — todos los núcleos activos": "Stops Windows from 'parking' CPU cores, keeping them all active. Advanced.",
  "MSI mode en la GPU (menos latencia)": "Enables message-signaled interrupts (MSI) on the GPU to reduce latency. Advanced: requires a restart.",
  "Deshabilitar algoritmo de Nagle (ping más bajo)": "Disables TCP packet batching, lowering latency in online games.",
  "Deshabilitar Teredo": "Turns off the Teredo IPv6 tunnel, which can cause connection issues in some games.",
  "Optimizar TCP": "Tunes TCP parameters (autotuning, RSS) for better network performance.",
  "Deshabilitar Large Send Offload (LSO)": "Disables LSO, which causes latency spikes on many network adapters.",
  "Reservar 0% de ancho de banda para QoS": "Frees the 20% of bandwidth Windows reserves for QoS by default. Advanced.",
  "Deshabilitar telemetría de Windows": "Reduces Windows diagnostic data collection to the minimum.",
  "Deshabilitar ID publicitario y Cortana": "Turns off the advertising ID and the Cortana assistant.",
  "Bloquear telemetría (archivo hosts)": "Adds Microsoft telemetry domains to the hosts file. WARNING: Windows Defender flags this as a threat (HostsFileHijack) and reverts it. Not needed: \"Disable Windows telemetry\" already blocks it via the registry.",
  "Desactivar Recall (captura de IA)": "Disables Windows 11 Recall, which takes periodic screenshots of your screen.",
  "Desactivar animaciones y efectos visuales": "Removes window and menu animations for a snappier response.",
  "Deshabilitar transparencia de Windows": "Turns off transparency effects, saving some GPU.",
  "Activar Modo Oscuro (apps y sistema)": "Switches Windows and apps to the dark theme.",
  "Quitar OneDrive por completo": "Uninstalls OneDrive and deletes its folder. Advanced: only do it if you don't use it.",
  "Deshabilitar SysMain / Superfetch": "Turns off the preload service, mostly useful on PCs with an SSD.",
  "Deshabilitar Windows Search (indexado)": "Turns off search indexing, which uses disk. Advanced: search becomes slower.",
  "Eliminar apps Microsoft innecesarias": "Removes Microsoft apps almost nobody uses (News, Weather, Solitaire, Maps, Teams, new Outlook, Copilot, Clipchamp…) for all users, and stops Windows from reinstalling them. Never touches Xbox/Game Pass, the Store or your games.",
  "Eliminar apps de terceros preinstaladas": "Removes third-party games and apps Windows installs as “suggestions” (Candy Crush, TikTok, Facebook, Netflix, Spotify, McAfee…) and keeps them from coming back. Doesn't touch Minecraft, Roblox or WhatsApp.",
  "Eliminar bloatware (lista completa)": "Everything from the two above plus Windows apps some people do use: Widgets, Sticky Notes, Sound Recorder, Quick Assist, Media Player, Paint 3D, Whiteboard… It's a fixed list: it never deletes apps you installed.",
  "Desinstalar Microsoft Edge (si usás otro navegador)": "Uninstalls Edge with its official uninstaller and stops Windows from reinstalling it. It only does it if you have another browser installed (Chrome, Firefox…). It doesn't touch WebView2, which other apps use. Undo it in Re-enable → Microsoft Edge.",
  "Desactivar HPET (timer de alta precisión)": "Disables the HPET timer and dynamic tick. On some PCs it lowers input latency; on others it makes it worse. Requires a restart. Advanced: try it and revert if you notice stutter.",
  "Deshabilitar OneDrive": "Uninstalls OneDrive and blocks it from syncing again. Files in your OneDrive folder are not deleted. Only do it if you don't use OneDrive.",
  "Deshabilitar tareas programadas de telemetría": "Turns off the tasks that send usage data to Microsoft (Customer Experience, Compatibility Appraiser, Disk Diagnostic…). Doesn't affect how Windows works.",
  "Deshabilitar Activity History y Timeline": "Windows stops saving and uploading your activity history (which apps and files you open).",
  "Reducir delay del menú contextual": "Menus open instantly instead of waiting ~0.4 s on hover.",
  "Simplificar barra de tareas (conservar buscador)": "Removes the Task View, Cortana and People buttons from the taskbar. Search stays.",
  "Desanclar todas las apps del menu Inicio": "Leaves the Start menu with no pinned apps (so you can set it up your way). Advanced: you'll have to pin the ones you use again.",
  "Desactivar panel de Widgets": "Removes the Widgets button (news, weather) from the taskbar and blocks it. Saves memory and background processes.",
  "Desactivar botón Chat / Teams en barra de tareas": "Removes the Chat/Teams button from the Windows 11 taskbar.",
  "Desactivar Copilot": "Removes the Copilot button and disables it by policy.",
  "Borrar accesos directos rotos (destino inexistente)": "Deletes desktop and Start menu shortcuts that point to programs that no longer exist.",
  "Deshabilitar permisos (excepto Cámara, Micrófono, Vídeos)": "Removes app access to location, contacts, calendar, files, Bluetooth and more. Camera and microphone stay. If an app stops working, use Re-enable → Permissions.",
  "Deshabilitar Activación por Voz": "Apps (like Cortana) stop listening for a wake word in the background.",
  "Deshabilitar apps en segundo plano": "Store apps don't run when you're not using them: less RAM and CPU. Note: Store apps (WhatsApp, Spotify…) may stop showing notifications.",
  "Deshabilitar notificaciones de apps": "Blocks app notifications. Fewer interruptions while gaming, but you won't see alerts from any app.",
  "Deshabilitar servicios de Xbox": "Turns off the Xbox services. Advanced: it breaks PC Game Pass (sign-in), cloud saves and Xbox controllers/accessories. Only if you don't use anything Xbox. Undo it in Re-enable → Xbox / Game Pass.",
  "Deshabilitar Remote Registry": "Prevents other PCs on the network from reading or changing your registry. Safer; almost nobody needs it.",
  "Deshabilitar Print Spooler (si no usas impresora)": "Turns off the print service. Advanced: you won't be able to print or use “Print to PDF” until you re-enable it (Re-enable → Printer).",
  "Deshabilitar Windows Defender (ADVERTENCIA: reduce proteccion)": "Turns off the Windows antivirus. Dangerous: your PC is left unprotected if you don't have another antivirus. On modern Windows, Tamper Protection usually blocks it: the app tells you if it couldn't.",
  "Menú contextual clásico (clic derecho de W10)": "Brings back the full Windows 10 right-click menu, without “Show more options”. Restarts Explorer.",
  "Mostrar extensiones de archivo": "Shows the extension (.exe, .pdf, .jpg…). Helps spot disguised dangerous files (e.g. “photo.jpg.exe”).",
  "Mostrar archivos y carpetas ocultos": "Shows hidden files and folders (like AppData) in Explorer.",
  "“Finalizar tarea” con clic derecho en la barra": "Adds “End task” to each app's right-click menu on the taskbar: close a frozen game without opening Task Manager.",
  "Alinear barra de tareas a la izquierda": "Moves the Start button and icons to the left, like in Windows 10.",
  "Desactivar Consumer Features (sugerencias y anuncios)": "Stops Windows from installing “suggested” apps on its own (Candy Crush and the like) and showing promotions.",
  "Quitar sugerencias/anuncios del menú Inicio": "Removes recommended apps and ads from the Start menu.",
  "Quitar búsqueda de Bing del menú Inicio": "Start search only searches your PC: faster and without Bing web results.",
  "Debloat de Microsoft Edge (quitar promos)": "Turns off Edge's shopping assistant, sidebar and recommendations. Doesn't uninstall Edge.",
  "Desactivar seguimiento de ubicación": "Turns off the Windows location service. Maps or weather apps won't know where you are.",
  "Desactivar Storage Sense": "Stops Windows from automatically deleting temp files or Recycle Bin items. Useful if you prefer cleaning manually.",
  "Desactivar Wi-Fi Sense": "Stops Windows from sharing or automatically joining suggested Wi-Fi networks.",
  "Desactivar telemetría de PowerShell 7": "PowerShell 7 stops sending usage data to Microsoft. Doesn't affect Windows PowerShell.",
  "Desactivar hibernación (libera espacio)": "Deletes the hibernation file (several GB). Advanced: it also disables Fast Startup and the Hibernate option.",
  "Desactivar IPv6": "Disables IPv6 on your network adapters. Advanced: some ISPs and games use it; if you lose connection, revert it.",
  "Desactivar reinicio automático tras actualizar": "Windows Update won't restart the PC on its own while someone is signed in (it won't cut off your game).",
  "Pantalla azul (BSOD) con detalles técnicos": "If a blue screen appears, it shows the code and the driver that caused it: helps find the problem.",
  "Mensajes detallados al iniciar sesión": "Shows what Windows is doing during startup and shutdown (useful if it takes too long).",
  "Activar NumLock al iniciar Windows": "The number pad stays on from the sign-in screen.",
  "Desactivar Sticky Keys": "Stops the Sticky Keys prompt when pressing Shift 5 times (very annoying in games).",
  "Mostrar segundos en el reloj de la barra": "The taskbar clock also shows seconds.",
  "Hora del sistema en UTC (dual-boot con Linux)": "Makes Windows read the PC clock as UTC, like Linux. Advanced: only if you dual-boot Linux and the time gets out of sync.",
  "Desactivar servicio HomeGroup": "Turns off the HomeGroup services (an old networking feature Windows 10/11 no longer uses).",
};
