// Generado automáticamente desde main.py — no editar a mano
export interface Tweak { name: string; script: string; os?: 10 | 11; risk?: "advanced"; }
export interface Category { id: string; name: string; color: string; tweaks: Tweak[]; }

export const CATEGORIES: Category[] = [
  {
    id: "gaming",
    name: "Gaming Performance",
    color: "#FF6B35",
    tweaks: [
      { name: "Plan de energía: Máximo rendimiento", script: "$hp = powercfg -list | Select-String \"High performance\" | Select-Object -First 1\nif ($hp) { $guid = ($hp -split '\\s+')[3]; powercfg /setactive $guid } else { powercfg /setactive SCHEME_MIN }\nWrite-Output \"Plan de energia configurado\"" },
      { name: "Habilitar Game Mode de Windows", script: "$path = 'HKCU:\\Software\\Microsoft\\GameBar'\nif (!(Test-Path $path)) { New-Item -Path $path -Force | Out-Null }\nSet-ItemProperty -Path $path -Name 'AutoGameModeEnabled' -Value 1 -Type DWord -Force\nWrite-Output \"Game Mode habilitado\"" },
      { name: "Deshabilitar Xbox Game Bar y DVR", script: "$p1 = 'HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\GameDVR'\n$p2 = 'HKCU:\\System\\GameConfigStore'\nforeach ($p in @($p1,$p2)) { if (!(Test-Path $p)) { New-Item -Path $p -Force | Out-Null } }\nSet-ItemProperty -Path $p1 -Name 'AppCaptureEnabled' -Value 0 -Type DWord -Force\nSet-ItemProperty -Path $p2 -Name 'GameDVR_Enabled'   -Value 0 -Type DWord -Force\nGet-AppxPackage 'Microsoft.XboxGamingOverlay' | Remove-AppxPackage -ErrorAction SilentlyContinue\nWrite-Output \"Xbox Game Bar deshabilitado\"" },
      { name: "Hardware Accelerated GPU Scheduling (HAGS)", script: "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers' -Name 'HwSchMode' -Value 2 -Type DWord -Force\nWrite-Output \"HAGS habilitado\"" },
      { name: "Prioridad CPU máxima para juegos", script: "$path = 'HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games'\nif (!(Test-Path $path)) { New-Item -Path $path -Force | Out-Null }\nSet-ItemProperty -Path $path -Name 'Priority'            -Value 6      -Type DWord  -Force\nSet-ItemProperty -Path $path -Name 'Scheduling Category' -Value 'High' -Type String -Force\nSet-ItemProperty -Path $path -Name 'SFIO Priority'       -Value 'High' -Type String -Force\nSet-ItemProperty -Path $path -Name 'GPU Priority'        -Value 8      -Type DWord  -Force\n$sys = 'HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile'\nSet-ItemProperty -Path $sys -Name 'SystemResponsiveness' -Value 0 -Type DWord -Force\nWrite-Output \"Prioridad CPU configurada\"" },
      { name: "Deshabilitar Full-Screen Optimization (FSO)", script: "$path = 'HKCU:\\System\\GameConfigStore'\nif (!(Test-Path $path)) { New-Item -Path $path -Force | Out-Null }\nSet-ItemProperty -Path $path -Name 'GameDVR_DXGIHonorFSEWindowsCompatible' -Value 1 -Type DWord -Force\nSet-ItemProperty -Path $path -Name 'GameDVR_FSEBehavior'                    -Value 2 -Type DWord -Force\nWrite-Output \"FSO deshabilitado\"" },
      { name: "Deshabilitar aceleración del mouse", script: "Set-ItemProperty -Path 'HKCU:\\Control Panel\\Mouse' -Name 'MouseSpeed'      -Value '0' -Type String -Force\nSet-ItemProperty -Path 'HKCU:\\Control Panel\\Mouse' -Name 'MouseThreshold1' -Value '0' -Type String -Force\nSet-ItemProperty -Path 'HKCU:\\Control Panel\\Mouse' -Name 'MouseThreshold2' -Value '0' -Type String -Force\nWrite-Output \"Aceleracion del mouse deshabilitada\"" },
      { name: "Timer Resolution — 1ms (reduce micro-stutters)", script: "# Activar solicitudes globales de alta resolucion de temporizador (Windows 10/11)\n$path = 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\kernel'\nif (!(Test-Path $path)) { New-Item -Path $path -Force | Out-Null }\nSet-ItemProperty -Path $path -Name 'GlobalTimerResolutionRequests' -Value 1 -Type DWord -Force\n\n# Crear tarea de inicio que fuerza 1ms via NtSetTimerResolution\n$taskScript = @'\nAdd-Type -TypeDefinition @\"\nusing System; using System.Runtime.InteropServices;\npublic class NtTimer {\n    [DllImport(\"ntdll.dll\")] public static extern int NtSetTimerResolution(uint r, bool set, ref uint cur);\n}\n\"@\n$cur = 0u\n[NtTimer]::NtSetTimerResolution(10000, $true, [ref]$cur)\n'@\n$scriptPath = \"$env:ProgramData\\GamingOptimizer\\SetTimerRes.ps1\"\nNew-Item -ItemType Directory -Path \"$env:ProgramData\\GamingOptimizer\" -Force | Out-Null\n$taskScript | Out-File $scriptPath -Encoding utf8 -Force\n\n$action  = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument \"-WindowStyle Hidden -NoProfile -ExecutionPolicy Bypass -File `\"$scriptPath`\"\"\n$trigger = New-ScheduledTaskTrigger -AtLogOn\n$settings = New-ScheduledTaskSettingsSet -Hidden\nRegister-ScheduledTask -TaskName 'GamingOptimizer_TimerRes' -Action $action -Trigger $trigger -Settings $settings -RunLevel Highest -Force -ErrorAction SilentlyContinue | Out-Null\n\n# Aplicar ahora mismo en esta sesion\ntry {\nAdd-Type -TypeDefinition @\"\nusing System; using System.Runtime.InteropServices;\npublic class NtTimer2 { [DllImport(\"ntdll.dll\")] public static extern int NtSetTimerResolution(uint r, bool set, ref uint cur); }\n\"@\n$cur2 = 0u\n[NtTimer2]::NtSetTimerResolution(10000, $true, [ref]$cur2)\nWrite-Output \"Timer Resolution: $([math]::Round($cur2/10000.0,2))ms (objetivo: 1ms)\"\n} catch { Write-Output \"Timer Resolution configurado (activo al reiniciar)\" }" },
      { name: "Core Parking OFF — todos los núcleos activos", script: "$scheme = (powercfg /getactivescheme) -replace '.*GUID: ([a-f0-9-]+).*','$1'\n# Minimo y maximo de nucleos activos al 100%\npowercfg /setacvalueindex $scheme SUB_PROCESSOR CPMINCORES 100 2>$null\npowercfg /setdcvalueindex $scheme SUB_PROCESSOR CPMINCORES 100 2>$null\npowercfg /setacvalueindex $scheme SUB_PROCESSOR CPMAXCORES 100 2>$null\npowercfg /setdcvalueindex $scheme SUB_PROCESSOR CPMAXCORES 100 2>$null\n# Frecuencia minima del procesador al 100% (sin throttling)\npowercfg /setacvalueindex $scheme SUB_PROCESSOR PROCTHROTTLEMIN 100 2>$null\npowercfg /setacvalueindex $scheme SUB_PROCESSOR PROCTHROTTLEMAX 100 2>$null\npowercfg /apply 2>$null\n# Tambien via registro para que sobreviva cambios de plan\n$regBase = 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Power\\PowerSettings\\54533251-82be-4824-96c1-47b60b740d00\\0cc5b647-c1df-4637-891a-dec35c318583'\nif (Test-Path $regBase) {\n    Set-ItemProperty -Path $regBase -Name 'ValueMax' -Value 100 -Type DWord -Force -ErrorAction SilentlyContinue\n    Set-ItemProperty -Path $regBase -Name 'ValueMin' -Value 100 -Type DWord -Force -ErrorAction SilentlyContinue\n}\nWrite-Output \"Core Parking deshabilitado — todos los nucleos activos\"" },
    ],
  },
  {
    id: "network",
    name: "Red — Menor Latencia",
    color: "#4CAF50",
    tweaks: [
      { name: "Deshabilitar algoritmo de Nagle (ping más bajo)", script: "$base = 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces'\nGet-ChildItem $base | ForEach-Object {\n    Set-ItemProperty -Path $_.PSPath -Name 'TcpAckFrequency' -Value 1 -Type DWord -Force -ErrorAction SilentlyContinue\n    Set-ItemProperty -Path $_.PSPath -Name 'TCPNoDelay'      -Value 1 -Type DWord -Force -ErrorAction SilentlyContinue\n}\nWrite-Output \"Algoritmo de Nagle deshabilitado\"" },
      { name: "Deshabilitar Teredo", script: "netsh interface teredo set state disabled | Out-Null\nWrite-Output \"Teredo deshabilitado\"" },
      { name: "Optimizar TCP", script: "netsh int tcp set global autotuninglevel=normal | Out-Null\nnetsh int tcp set global chimney=disabled       | Out-Null\nnetsh int tcp set global rss=enabled            | Out-Null\nnetsh int tcp set global dca=enabled            | Out-Null\nWrite-Output \"TCP optimizado\"" },
      { name: "Deshabilitar Large Send Offload (LSO)", script: "Get-NetAdapter -Physical | ForEach-Object { Disable-NetAdapterLso -Name $_.Name -ErrorAction SilentlyContinue }\nWrite-Output \"LSO deshabilitado\"" },
      { name: "Reservar 0% de ancho de banda para QoS", script: "$path = 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Psched'\nif (!(Test-Path $path)) { New-Item -Path $path -Force | Out-Null }\nSet-ItemProperty -Path $path -Name 'NonBestEffortLimit' -Value 0 -Type DWord -Force\nWrite-Output \"QoS bandwidth al 100 para juegos\"" },
    ],
  },
  {
    id: "debloat",
    name: "Eliminar Bloatware",
    color: "#2196F3",
    tweaks: [
      { name: "[Sycnex] Remove ALL Bloatware (lista completa)", script: "$WhitelistedApps = 'Microsoft.ScreenSketch|Microsoft.Paint3D|Microsoft.WindowsCalculator|Microsoft.WindowsStore|Microsoft.Windows.Photos|CanonicalGroupLimited.UbuntuonWindows|Microsoft.XboxGameCallableUI|Microsoft.XboxGamingOverlay|Microsoft.Xbox.TCUI|Microsoft.XboxIdentityProvider|Microsoft.MicrosoftStickyNotes|Microsoft.MSPaint|Microsoft.WindowsCamera|.NET|Framework|Microsoft.HEIFImageExtension|Microsoft.StorePurchaseApp|Microsoft.VP9VideoExtensions|Microsoft.WebMediaExtensions|Microsoft.WebpImageExtension|Microsoft.DesktopAppInstaller|WindSynthBerry|MIDIBerry|Slack'\n$NonRemovable = '1527c705-839a-4832-9118-54d4Bd6a0c89|c5e2524a-ea46-4f67-841f-6a9465d9d515|E2A4F912-2574-4A75-9BB0-0D023378592B|F46D4000-FD22-4DB4-AC8E-4E1DDDE828FE|InputApp|Microsoft.AAD.BrokerPlugin|Microsoft.AccountsControl|Microsoft.BioEnrollment|Microsoft.CredDialogHost|Microsoft.ECApp|Microsoft.LockApp|Microsoft.MicrosoftEdgeDevToolsClient|Microsoft.MicrosoftEdge|Microsoft.PPIProjection|Microsoft.Win32WebViewHost|Microsoft.Windows.Apprep.ChxApp|Microsoft.Windows.AssignedAccessLockApp|Microsoft.Windows.CapturePicker|Microsoft.Windows.CloudExperienceHost|Microsoft.Windows.ContentDeliveryManager|Microsoft.Windows.Cortana|Microsoft.Windows.NarratorQuickStart|Microsoft.Windows.ParentalControls|Microsoft.Windows.PeopleExperienceHost|Microsoft.Windows.PinningConfirmationDialog|Microsoft.Windows.SecHealthUI|Microsoft.Windows.SecureAssessmentBrowser|Microsoft.Windows.ShellExperienceHost|Microsoft.Windows.XGpuEjectDialog|Microsoft.XboxGameCallableUI|Windows.CBSPreview|windows.immersivecontrolpanel|Windows.PrintDialog|Microsoft.VCLibs.140.00|Microsoft.Services.Store.Engagement|Microsoft.UI.Xaml.2.0|*Nvidia*'\nWrite-Output \"Eliminando bloatware...\"\nGet-AppxPackage -AllUsers | Where-Object { $_.Name -NotMatch $WhitelistedApps -and $_.Name -NotMatch $NonRemovable } | Remove-AppxPackage -ErrorAction SilentlyContinue\nGet-AppxPackage           | Where-Object { $_.Name -NotMatch $WhitelistedApps -and $_.Name -NotMatch $NonRemovable } | Remove-AppxPackage -ErrorAction SilentlyContinue\nGet-AppxProvisionedPackage -Online | Where-Object { $_.PackageName -NotMatch $WhitelistedApps -and $_.PackageName -NotMatch $NonRemovable } | Remove-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue\nWrite-Output \"Bloatware eliminado (Sycnex DebloatAll)\"" },
      { name: "[Sycnex] Remove Bloatware por lista negra", script: "$Bloatware = @(\n    'Microsoft.BingNews','Microsoft.GetHelp','Microsoft.Getstarted',\n    'Microsoft.Messaging','Microsoft.Microsoft3DViewer','Microsoft.MicrosoftOfficeHub',\n    'Microsoft.MicrosoftSolitaireCollection','Microsoft.NetworkSpeedTest','Microsoft.News',\n    'Microsoft.Office.Lens','Microsoft.Office.OneNote','Microsoft.Office.Sway',\n    'Microsoft.OneConnect','Microsoft.People','Microsoft.Print3D',\n    'Microsoft.RemoteDesktop','Microsoft.SkypeApp','Microsoft.StorePurchaseApp',\n    'Microsoft.Office.Todo.List','Microsoft.Whiteboard','Microsoft.WindowsAlarms',\n    'microsoft.windowscommunicationsapps','Microsoft.WindowsFeedbackHub',\n    'Microsoft.WindowsMaps','Microsoft.WindowsSoundRecorder','Microsoft.Xbox.TCUI',\n    'Microsoft.XboxApp','Microsoft.XboxGameOverlay','Microsoft.XboxIdentityProvider',\n    'Microsoft.XboxSpeechToTextOverlay','Microsoft.ZuneMusic','Microsoft.ZuneVideo',\n    '*EclipseManager*','*ActiproSoftwareLLC*',\n    '*AdobeSystemsIncorporated.AdobePhotoshopExpress*','*Duolingo-LearnLanguagesforFree*',\n    '*PandoraMediaInc*','*CandyCrush*','*BubbleWitch3Saga*','*Wunderlist*',\n    '*Flipboard*','*Twitter*','*Facebook*','*Spotify*','*Minecraft*',\n    '*Royal Revolt*','*Sway*','*Speed Test*','*Dolby*'\n)\nforeach ($Bloat in $Bloatware) {\n    Get-AppxPackage -Name $Bloat | Remove-AppxPackage -ErrorAction SilentlyContinue\n    Get-AppxProvisionedPackage -Online | Where-Object DisplayName -like $Bloat | Remove-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue\n}\nWrite-Output \"Lista negra eliminada\"" },
      { name: "Eliminar apps Microsoft innecesarias", script: "$apps = @(\n    'Microsoft.BingNews','Microsoft.BingWeather','Microsoft.GetHelp','Microsoft.Getstarted',\n    'Microsoft.Messaging','Microsoft.Microsoft3DViewer','Microsoft.MicrosoftSolitaireCollection',\n    'Microsoft.MicrosoftOfficeHub','Microsoft.NetworkSpeedTest','Microsoft.News',\n    'Microsoft.Office.Sway','Microsoft.OneConnect','Microsoft.People','Microsoft.Print3D',\n    'Microsoft.SkypeApp','Microsoft.Wallet','Microsoft.WindowsAlarms',\n    'Microsoft.WindowsFeedbackHub','Microsoft.WindowsMaps','Microsoft.WindowsSoundRecorder',\n    'Microsoft.ZuneMusic','Microsoft.ZuneVideo','Microsoft.YourPhone',\n    'Microsoft.MixedReality.Portal','MicrosoftTeams'\n)\nforeach ($app in $apps) {\n    Get-AppxPackage -Name $app -AllUsers   | Remove-AppxPackage -AllUsers -ErrorAction SilentlyContinue\n    Get-AppxProvisionedPackage -Online | Where-Object DisplayName -like $app | Remove-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue\n}\nWrite-Output \"Apps Microsoft eliminadas\"" },
      { name: "Eliminar apps de terceros preinstaladas", script: "$patterns = @('*CandyCrush*','*Duolingo*','*EclipseManager*','*AdobeSystemsIncorporated.AdobePhotoshopExpress*',\n    '*BubbleWitch3Saga*','*Wunderlist*','*Flipboard*','*Twitter*','*Facebook*','*Spotify*',\n    '*Minecraft*','*RoyalRevolt*','*Dolby*','*Netflix*','*PandoraMediaInc*','*TikTok*','*WhatsApp*')\nforeach ($p in $patterns) { Get-AppxPackage -Name $p | Remove-AppxPackage -ErrorAction SilentlyContinue }\nWrite-Output \"Apps de terceros eliminadas\"" },
      { name: "Deshabilitar OneDrive", script: "Stop-Process -Name 'OneDrive' -Force -ErrorAction SilentlyContinue\nif (Test-Path \"$env:SystemRoot\\SysWOW64\\OneDriveSetup.exe\") { & \"$env:SystemRoot\\SysWOW64\\OneDriveSetup.exe\" /uninstall 2>$null }\nelseif (Test-Path \"$env:SystemRoot\\System32\\OneDriveSetup.exe\")  { & \"$env:SystemRoot\\System32\\OneDriveSetup.exe\"  /uninstall 2>$null }\n$path = 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\OneDrive'\nif (!(Test-Path $path)) { New-Item -Path $path -Force | Out-Null }\nSet-ItemProperty -Path $path -Name 'DisableFileSyncNGSC' -Value 1 -Type DWord -Force\nWrite-Output \"OneDrive deshabilitado\"" },
    ],
  },
  {
    id: "privacy",
    name: "Privacidad y Telemetría",
    color: "#9C27B0",
    tweaks: [
      { name: "Deshabilitar telemetría de Windows", script: "$paths = @('HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\DataCollection',\n           'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection',\n           'HKLM:\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Policies\\DataCollection')\nforeach ($p in $paths) {\n    if (!(Test-Path $p)) { New-Item -Path $p -Force | Out-Null }\n    Set-ItemProperty -Path $p -Name 'AllowTelemetry' -Value 0 -Type DWord -Force\n}\nStop-Service 'DiagTrack' -ErrorAction SilentlyContinue; Set-Service 'DiagTrack' -StartupType Disabled -ErrorAction SilentlyContinue\nStop-Service 'dmwappushservice' -ErrorAction SilentlyContinue; Set-Service 'dmwappushservice' -StartupType Disabled -ErrorAction SilentlyContinue\nWrite-Output \"Telemetria deshabilitada\"" },
      { name: "Deshabilitar tareas programadas de telemetría", script: "$tasks = @(\n    '\\Microsoft\\Windows\\Application Experience\\Microsoft Compatibility Appraiser',\n    '\\Microsoft\\Windows\\Application Experience\\ProgramDataUpdater',\n    '\\Microsoft\\Windows\\Autochk\\Proxy',\n    '\\Microsoft\\Windows\\Customer Experience Improvement Program\\Consolidator',\n    '\\Microsoft\\Windows\\Customer Experience Improvement Program\\UsbCeip',\n    '\\Microsoft\\Windows\\DiskDiagnostic\\Microsoft-Windows-DiskDiagnosticDataCollector',\n    '\\Microsoft\\Windows\\Feedback\\Siuf\\DmClient',\n    '\\Microsoft\\Windows\\Windows Error Reporting\\QueueReporting',\n    '\\Microsoft\\Windows\\Xbox\\XblGameSaveTask'\n)\nforeach ($t in $tasks) { Disable-ScheduledTask -TaskPath (Split-Path $t) -TaskName (Split-Path $t -Leaf) -ErrorAction SilentlyContinue }\nWrite-Output \"Tareas de telemetria deshabilitadas\"" },
      { name: "Deshabilitar ID publicitario y Cortana", script: "$adPath = 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\AdvertisingInfo'\nif (!(Test-Path $adPath)) { New-Item -Path $adPath -Force | Out-Null }\nSet-ItemProperty -Path $adPath -Name 'Enabled' -Value 0 -Type DWord -Force\n$cortanaPath = 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search'\nif (!(Test-Path $cortanaPath)) { New-Item -Path $cortanaPath -Force | Out-Null }\nSet-ItemProperty -Path $cortanaPath -Name 'AllowCortana'         -Value 0 -Type DWord -Force\nSet-ItemProperty -Path $cortanaPath -Name 'DisableWebSearch'     -Value 1 -Type DWord -Force\nSet-ItemProperty -Path $cortanaPath -Name 'ConnectedSearchUseWeb'-Value 0 -Type DWord -Force\nWrite-Output \"ID publicitario y Cortana deshabilitados\"" },
      { name: "Deshabilitar Activity History y Timeline", script: "$path = 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System'\nif (!(Test-Path $path)) { New-Item -Path $path -Force | Out-Null }\nSet-ItemProperty -Path $path -Name 'EnableActivityFeed'    -Value 0 -Type DWord -Force\nSet-ItemProperty -Path $path -Name 'PublishUserActivities' -Value 0 -Type DWord -Force\nSet-ItemProperty -Path $path -Name 'UploadUserActivities'  -Value 0 -Type DWord -Force\nWrite-Output \"Activity History deshabilitado\"" },
    ],
  },
  {
    id: "visual",
    name: "Rendimiento Visual",
    color: "#FF9800",
    tweaks: [
      { name: "Desactivar animaciones y efectos visuales", script: "$adv  = 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced'\n$desk = 'HKCU:\\Control Panel\\Desktop'\n$win  = 'HKCU:\\Control Panel\\Desktop\\WindowMetrics'\n$dwm  = 'HKCU:\\Software\\Microsoft\\Windows\\DWM'\nSet-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\VisualEffects' -Name 'VisualFXSetting' -Value 3 -Type DWord -Force\nSet-ItemProperty -Path $adv  -Name 'TaskbarAnimations'    -Value 0   -Type DWord  -Force\nSet-ItemProperty -Path $win  -Name 'MinAnimate'           -Value '0' -Type String -Force\nSet-ItemProperty -Path $adv  -Name 'ListviewAlphaSelect'  -Value 0   -Type DWord  -Force\nSet-ItemProperty -Path $adv  -Name 'ListviewShadow'       -Value 0   -Type DWord  -Force\nSet-ItemProperty -Path $desk -Name 'MenuShowDelay'        -Value '0' -Type String -Force\nSet-ItemProperty -Path $desk -Name 'UserPreferencesMask'  -Value ([byte[]](0x90,0x12,0x01,0x80,0x10,0x00,0x00,0x00)) -Type Binary -Force\nif (!(Test-Path $dwm)) { New-Item -Path $dwm -Force | Out-Null }\nSet-ItemProperty -Path $dwm  -Name 'EnableAeroPeek'        -Value 0 -Type DWord -Force\nSet-ItemProperty -Path $adv  -Name 'DisablePreviewDesktop' -Value 1 -Type DWord -Force\nSet-ItemProperty -Path $desk -Name 'DragFullWindows'        -Value '1' -Type String -Force\nSet-ItemProperty -Path $desk -Name 'FontSmoothing'          -Value '2' -Type String -Force\nSet-ItemProperty -Path $desk -Name 'FontSmoothingType'      -Value 2   -Type DWord  -Force\nSet-ItemProperty -Path $adv  -Name 'IconsOnly'              -Value 0   -Type DWord  -Force\nWrite-Output \"Efectos visuales optimizados\"" },
      { name: "Deshabilitar transparencia de Windows", script: "Set-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize' -Name 'EnableTransparency' -Value 0 -Type DWord -Force\nWrite-Output \"Transparencia deshabilitada\"" },
      { name: "Reducir delay del menú contextual", script: "Set-ItemProperty -Path 'HKCU:\\Control Panel\\Desktop' -Name 'MenuShowDelay' -Value '0' -Type String -Force\nWrite-Output \"Delay del menu reducido\"" },
    ],
  },
  {
    id: "desktop",
    name: "Escritorio y Apariencia",
    color: "#607D8B",
    tweaks: [
      { name: "Activar Modo Oscuro (apps y sistema)", script: "$path = 'HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize'\nif (!(Test-Path $path)) { New-Item -Path $path -Force | Out-Null }\nSet-ItemProperty -Path $path -Name 'AppsUseLightTheme'    -Value 0 -Type DWord -Force\nSet-ItemProperty -Path $path -Name 'SystemUsesLightTheme' -Value 0 -Type DWord -Force\nWrite-Output \"Modo oscuro activado\"" },
      { name: "Simplificar barra de tareas (conservar buscador)", script: "$adv = 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced'\n# Ocultar boton Task View\nSet-ItemProperty -Path $adv -Name 'ShowTaskViewButton' -Value 0 -Type DWord -Force -ErrorAction SilentlyContinue\n# Ocultar boton Cortana\nSet-ItemProperty -Path $adv -Name 'ShowCortanaButton'  -Value 0 -Type DWord -Force -ErrorAction SilentlyContinue\n# Ocultar icono People (contactos)\nSet-ItemProperty -Path $adv -Name 'PeopleBand'          -Value 0 -Type DWord -Force -ErrorAction SilentlyContinue\n# Ocultar Noticias y tiempo (widgets Windows 10)\nSet-ItemProperty -Path $adv -Name 'TaskbarDa'           -Value 0 -Type DWord -Force -ErrorAction SilentlyContinue\n# Ocultar Meet Now (camara rapida)\n$pol = 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer'\nif (!(Test-Path $pol)) { New-Item -Path $pol -Force | Out-Null }\nSet-ItemProperty -Path $pol -Name 'HideSCAMeetNow'      -Value 1 -Type DWord -Force\n# Mantener buscador visible (modo barra completa = 2, solo icono = 1)\nSet-ItemProperty -Path $adv -Name 'SearchboxTaskbarMode' -Value 1 -Type DWord -Force -ErrorAction SilentlyContinue\nWrite-Output \"Barra de tareas simplificada (buscador conservado)\"" },
      { name: "Desanclar todas las apps del menu Inicio", script: "$blankLayout = @'\n<LayoutModificationTemplate\n    xmlns=\"http://schemas.microsoft.com/Start/2014/LayoutModification\"\n    xmlns:defaultlayout=\"http://schemas.microsoft.com/Start/2014/FullDefaultLayout\"\n    xmlns:start=\"http://schemas.microsoft.com/Start/2014/StartLayout\"\n    Version=\"1\">\n  <LayoutOptions StartTileGroupsColumnCount=\"4\" />\n  <DefaultLayoutOverride>\n    <StartLayoutCollection>\n      <defaultlayout:StartLayout GroupCellWidth=\"4\" />\n    </StartLayoutCollection>\n  </DefaultLayoutOverride>\n</LayoutModificationTemplate>\n'@\n$layoutFile = \"$env:TEMP\\BlankStart.xml\"\n$blankLayout | Out-File $layoutFile -Encoding utf8 -Force\ntry {\n    Import-StartLayout -LayoutPath $layoutFile -MountPath \"$env:SystemDrive\\\" -ErrorAction Stop\n    Write-Output \"Apps del Inicio desancladas (reinicia para ver los cambios)\"\n} catch {\n    # Metodo alternativo: borrar base de datos de tiles\n    $db = \"$env:LOCALAPPDATA\\TileDataLayer\\Database\"\n    if (Test-Path $db) {\n        Stop-Process -Name 'explorer' -Force -ErrorAction SilentlyContinue\n        Start-Sleep 1\n        Remove-Item $db -Recurse -Force -ErrorAction SilentlyContinue\n        Start-Process explorer\n    }\n    Write-Output \"Apps del Inicio desancladas (metodo alternativo)\"\n}" },
      { name: "Desactivar panel de Widgets", script: "$path = 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced'\nSet-ItemProperty -Path $path -Name 'TaskbarDa' -Value 0 -Type DWord -Force -ErrorAction SilentlyContinue\n$pol = 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Dsh'\nif (!(Test-Path $pol)) { New-Item -Path $pol -Force | Out-Null }\nSet-ItemProperty -Path $pol -Name 'AllowNewsAndInterests' -Value 0 -Type DWord -Force -ErrorAction SilentlyContinue\nWrite-Output \"Panel de Widgets desactivado\"", os: 11 },
      { name: "Desactivar botón Chat / Teams en barra de tareas", script: "$path = 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced'\nSet-ItemProperty -Path $path -Name 'TaskbarMn' -Value 0 -Type DWord -Force -ErrorAction SilentlyContinue\nWrite-Output \"Boton Chat/Teams eliminado de la barra de tareas\"", os: 11 },
      { name: "Desactivar Copilot", script: "$adv = 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced'\nSet-ItemProperty -Path $adv -Name 'ShowCopilotButton' -Value 0 -Type DWord -Force -ErrorAction SilentlyContinue\n$pol = 'HKCU:\\Software\\Policies\\Microsoft\\Windows\\WindowsCopilot'\nif (!(Test-Path $pol)) { New-Item -Path $pol -Force | Out-Null }\nSet-ItemProperty -Path $pol -Name 'TurnOffWindowsCopilot' -Value 1 -Type DWord -Force -ErrorAction SilentlyContinue\nWrite-Output \"Copilot desactivado\"", os: 11 },
      { name: "Borrar accesos directos rotos (destino inexistente)", script: "$dirs = @(\n    [System.Environment]::GetFolderPath('Desktop'),\n    [System.Environment]::GetFolderPath('CommonDesktopDirectory'),\n    \"$env:APPDATA\\Microsoft\\Windows\\Start Menu\\Programs\",\n    \"$env:ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\"\n)\n$shell   = New-Object -ComObject WScript.Shell\n$removed = 0\nforeach ($dir in $dirs) {\n    if (!(Test-Path $dir)) { continue }\n    Get-ChildItem -Path $dir -Filter '*.lnk' -Recurse -ErrorAction SilentlyContinue | ForEach-Object {\n        try {\n            $target = $shell.CreateShortcut($_.FullName).TargetPath\n            if ($target -and !(Test-Path $target)) {\n                Remove-Item $_.FullName -Force -ErrorAction SilentlyContinue\n                $removed++\n            }\n        } catch {}\n    }\n}\n[System.Runtime.InteropServices.Marshal]::ReleaseComObject($shell) | Out-Null\nWrite-Output \"Accesos directos rotos eliminados: $removed\"" },
    ],
  },
  {
    id: "permisos",
    name: "Permisos de Aplicaciones",
    color: "#00BCD4",
    tweaks: [
      { name: "Deshabilitar permisos (excepto Cámara, Micrófono, Vídeos)", script: "$base = 'HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore'\n$deny = @('location','userAccountInformation','contacts','appointments','phoneCall','phoneCallHistory',\n    'email','userDataTasks','chat','radios','bluetoothSync','appDiagnostics','documentsLibrary',\n    'picturesLibrary','broadFileSystemAccess','backgroundSpatialPerception','gazeInput','activity',\n    'trackerPlugin','graphicsCaptureProgrammatic','graphicsCaptureWithoutBorder')\nforeach ($p in $deny) {\n    $path = \"$base\\$p\"\n    if (!(Test-Path $path)) { New-Item -Path $path -Force | Out-Null }\n    Set-ItemProperty -Path $path -Name 'Value' -Value 'Deny' -Type String -Force\n}\nforeach ($p in @('microphone','webcam','videosLibrary')) {\n    $path = \"$base\\$p\"\n    if (!(Test-Path $path)) { New-Item -Path $path -Force | Out-Null }\n    Set-ItemProperty -Path $path -Name 'Value' -Value 'Allow' -Type String -Force\n}\nWrite-Output \"Permisos configurados (camara/microfono/videos mantenidos)\"" },
      { name: "Deshabilitar Activación por Voz", script: "$path = 'HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\voiceActivation'\nif (!(Test-Path $path)) { New-Item -Path $path -Force | Out-Null }\nSet-ItemProperty -Path $path -Name 'Value' -Value 'Deny' -Type String -Force\n$pol = 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy'\nif (!(Test-Path $pol)) { New-Item -Path $pol -Force | Out-Null }\nSet-ItemProperty -Path $pol -Name 'LetAppsActivateWithVoice' -Value 2 -Type DWord -Force\nWrite-Output \"Activacion por voz deshabilitada\"" },
      { name: "Deshabilitar apps en segundo plano", script: "$path = 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\BackgroundAccessApplications'\nif (!(Test-Path $path)) { New-Item -Path $path -Force | Out-Null }\nSet-ItemProperty -Path $path -Name 'GlobalUserDisabled' -Value 1 -Type DWord -Force\nWrite-Output \"Apps en segundo plano deshabilitadas\"" },
      { name: "Deshabilitar notificaciones de apps", script: "$path = 'HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\userNotificationListener'\nif (!(Test-Path $path)) { New-Item -Path $path -Force | Out-Null }\nSet-ItemProperty -Path $path -Name 'Value' -Value 'Deny' -Type String -Force\nWrite-Output \"Notificaciones de apps deshabilitadas\"" },
    ],
  },
  {
    id: "services",
    name: "Servicios Innecesarios",
    color: "#F44336",
    tweaks: [
      { name: "Deshabilitar SysMain / Superfetch", script: "Stop-Service 'SysMain' -ErrorAction SilentlyContinue; Set-Service 'SysMain' -StartupType Disabled -ErrorAction SilentlyContinue\nWrite-Output \"SysMain deshabilitado\"" },
      { name: "Deshabilitar Windows Search (indexado)", script: "Stop-Service 'WSearch' -ErrorAction SilentlyContinue; Set-Service 'WSearch' -StartupType Disabled -ErrorAction SilentlyContinue\nWrite-Output \"Windows Search deshabilitado\"" },
      { name: "Deshabilitar servicios de Xbox", script: "foreach ($svc in @('XblAuthManager','XblGameSave','XboxGipSvc','XboxNetApiSvc')) {\n    Stop-Service $svc -ErrorAction SilentlyContinue; Set-Service $svc -StartupType Disabled -ErrorAction SilentlyContinue\n}\nWrite-Output \"Servicios Xbox deshabilitados\"" },
      { name: "Deshabilitar Remote Registry", script: "Stop-Service 'RemoteRegistry' -ErrorAction SilentlyContinue; Set-Service 'RemoteRegistry' -StartupType Disabled -ErrorAction SilentlyContinue\nWrite-Output \"Remote Registry deshabilitado\"" },
      { name: "Deshabilitar Print Spooler (si no usas impresora)", script: "Stop-Service 'Spooler' -ErrorAction SilentlyContinue; Set-Service 'Spooler' -StartupType Disabled -ErrorAction SilentlyContinue\nWrite-Output \"Print Spooler deshabilitado\"" },
      { name: "Deshabilitar Windows Defender (ADVERTENCIA: reduce proteccion)", script: "# 1. Deshabilitar Tamper Protection via registro\n$tp = 'HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Features'\nif (Test-Path $tp) {\n    Set-ItemProperty -Path $tp -Name 'TamperProtection' -Value 0 -Type DWord -Force -ErrorAction SilentlyContinue\n}\n\n# 2. Deshabilitar via Group Policy (metodo mas permanente)\n$pol = 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender'\nif (!(Test-Path $pol)) { New-Item -Path $pol -Force | Out-Null }\nSet-ItemProperty -Path $pol -Name 'DisableAntiSpyware'       -Value 1 -Type DWord -Force\nSet-ItemProperty -Path $pol -Name 'DisableAntiVirus'         -Value 1 -Type DWord -Force\n\n$rt = \"$pol\\Real-Time Protection\"\nif (!(Test-Path $rt)) { New-Item -Path $rt -Force | Out-Null }\nSet-ItemProperty -Path $rt -Name 'DisableRealtimeMonitoring' -Value 1 -Type DWord -Force\nSet-ItemProperty -Path $rt -Name 'DisableBehaviorMonitoring' -Value 1 -Type DWord -Force\nSet-ItemProperty -Path $rt -Name 'DisableOnAccessProtection' -Value 1 -Type DWord -Force\nSet-ItemProperty -Path $rt -Name 'DisableScanOnRealtimeEnable' -Value 1 -Type DWord -Force\n\n# 3. Deshabilitar servicios de Defender\n$svcs = @('WinDefend','WdNisSvc','WdNisDrv','Sense','WdFilter','WdBoot')\nforeach ($svc in $svcs) {\n    Stop-Service $svc -Force -ErrorAction SilentlyContinue\n    Set-Service  $svc -StartupType Disabled -ErrorAction SilentlyContinue\n}\n\n# 4. Deshabilitar tareas programadas de Defender\n$defTasks = @(\n    '\\Microsoft\\Windows\\Windows Defender\\Windows Defender Cache Maintenance',\n    '\\Microsoft\\Windows\\Windows Defender\\Windows Defender Cleanup',\n    '\\Microsoft\\Windows\\Windows Defender\\Windows Defender Scheduled Scan',\n    '\\Microsoft\\Windows\\Windows Defender\\Windows Defender Verification'\n)\nforeach ($t in $defTasks) {\n    Disable-ScheduledTask -TaskPath (Split-Path $t) -TaskName (Split-Path $t -Leaf) -ErrorAction SilentlyContinue\n}\n\n# 5. Intentar via PowerShell (puede fallar si Tamper Protection sigue activa)\ntry { Set-MpPreference -DisableRealtimeMonitoring $true -ErrorAction SilentlyContinue } catch {}\n\nWrite-Output \"Windows Defender deshabilitado (reinicia para aplicar completamente)\"" },
    ],
  },
];
