// Descripciones cortas de qué hace cada tweak (para los tooltips)
export const TWEAK_DESC: Record<string, string> = {
  "Plan de energía: Máximo rendimiento": "Activa el plan Ultimate Performance (o Alto rendimiento si tu Windows no lo tiene): la CPU no baja su frecuencia para ahorrar, ideal para juegos. Reutiliza el plan si ya existe, no crea copias.",
  "Habilitar Game Mode de Windows": "Prioriza recursos para el juego en primer plano y reduce tareas de fondo mientras jugás.",
  "Deshabilitar Xbox Game Bar y DVR": "Apaga la grabación en segundo plano del Game Bar, que consume CPU/GPU y puede causar tirones.",
  "Hardware Accelerated GPU Scheduling (HAGS)": "Deja que la GPU gestione su propia memoria/planificación, bajando la latencia en tarjetas modernas.",
  "Prioridad CPU máxima para juegos": "Sube la prioridad de CPU/GPU para tareas de juego en el registro de Windows.",
  "Deshabilitar Full-Screen Optimization (FSO)": "Fuerza pantalla completa exclusiva real, reduciendo input lag en algunos juegos.",
  "Deshabilitar aceleración del mouse": "Hace que el movimiento del mouse sea 1:1 (sin aceleración), clave para apuntar en shooters.",
  "Timer Resolution — 1ms (reduce micro-stutters)": "Fuerza el temporizador del sistema a 1ms para suavizar micro-tirones. Avanzado: crea una tarea al inicio.",
  "Core Parking OFF — todos los núcleos activos": "Evita que Windows 'aparque' núcleos de la CPU, manteniéndolos todos activos. Avanzado.",
  "Deshabilitar algoritmo de Nagle (ping más bajo)": "Desactiva el agrupado de paquetes TCP, bajando la latencia en juegos online.",
  "Deshabilitar Teredo": "Apaga el túnel IPv6 Teredo, que puede causar problemas de conexión en algunos juegos.",
  "Optimizar TCP": "Ajusta parámetros TCP (autotuning, RSS) para mejor rendimiento de red.",
  "Deshabilitar Large Send Offload (LSO)": "Desactiva LSO, que en muchas placas de red causa picos de latencia.",
  "Reservar 0% de ancho de banda para QoS": "Libera el 20% de ancho de banda que Windows reserva por defecto para QoS. Avanzado.",
  "MSI mode en la GPU (menos latencia)": "Activa interrupciones por mensaje (MSI) en la GPU para reducir latencia. Avanzado: requiere reiniciar.",
  "Bloquear telemetría (archivo hosts)": "Agrega los dominios de telemetría de Microsoft al archivo hosts. OJO: Windows Defender lo detecta como amenaza (HostsFileHijack) y revierte los cambios. No hace falta: \"Deshabilitar telemetría de Windows\" ya la corta por registro.",
  "Desactivar Recall (captura de IA)": "Desactiva Recall de Windows 11, que toma capturas periódicas de tu pantalla.",
  "Quitar OneDrive por completo": "Desinstala OneDrive y borra su carpeta. Avanzado: hacelo solo si no lo usás.",
  "Deshabilitar telemetría de Windows": "Reduce al mínimo la recolección de datos de diagnóstico de Windows.",
  "Deshabilitar ID publicitario y Cortana": "Apaga el identificador de publicidad y la asistente Cortana.",
  "Desactivar animaciones y efectos visuales": "Quita animaciones de ventanas y menús para una respuesta más rápida.",
  "Deshabilitar transparencia de Windows": "Apaga los efectos de transparencia, ahorrando algo de GPU.",
  "Activar Modo Oscuro (apps y sistema)": "Pone Windows y las apps en tema oscuro.",
  "Deshabilitar SysMain / Superfetch": "Apaga el servicio de precarga, útil sobre todo en equipos con SSD.",
  "Deshabilitar Windows Search (indexado)": "Apaga la indexación de búsqueda, que consume disco. Avanzado: la búsqueda se vuelve más lenta.",
  "Eliminar apps Microsoft innecesarias": "Quita apps de Microsoft que casi nadie usa (Noticias, Clima, Solitario, Mapas, Teams, Outlook nuevo, Copilot, Clipchamp…) para todos los usuarios, y evita que Windows las reinstale. Nunca toca Xbox/Game Pass, la Store ni tus juegos.",
  "Eliminar apps de terceros preinstaladas": "Quita juegos y apps de terceros que Windows instala como “sugerencia” (Candy Crush, TikTok, Facebook, Netflix, Spotify, McAfee…) y evita que vuelvan. No toca Minecraft, Roblox ni WhatsApp.",
  "Eliminar bloatware (lista completa)": "Todo lo de las dos anteriores más apps de Windows que algunos sí usan: Widgets, Notas rápidas, Grabadora, Asistencia rápida, Reproductor multimedia, Paint 3D, Whiteboard… Es una lista fija: nunca borra apps que instalaste vos.",
  "Desinstalar Microsoft Edge (si usás otro navegador)": "Desinstala Edge con su desinstalador oficial y evita que Windows lo reinstale. Solo lo hace si tenés otro navegador instalado (Chrome, Firefox…). No toca WebView2, que usan otras apps. Se revierte en Reactivar → Microsoft Edge.",
  "Desactivar HPET (timer de alta precisión)": "Desactiva el temporizador HPET y el “dynamic tick”. En algunas PCs baja la latencia de entrada; en otras empeora. Requiere reiniciar. Avanzado: probalo y revertilo si notás tirones.",
  "Deshabilitar OneDrive": "Desinstala OneDrive y bloquea que se vuelva a sincronizar. Tus archivos de la carpeta OneDrive no se borran. Hacelo solo si no usás OneDrive.",
  "Deshabilitar tareas programadas de telemetría": "Apaga las tareas que envían datos de uso a Microsoft (Experiencia de cliente, Compatibilidad, Diagnóstico de disco…). No afecta el funcionamiento de Windows.",
  "Deshabilitar Activity History y Timeline": "Windows deja de guardar y subir tu historial de actividad (qué apps y archivos abrís).",
  "Reducir delay del menú contextual": "Los menús se abren al instante en vez de esperar ~0,4 s al pasar el mouse.",
  "Simplificar barra de tareas (conservar buscador)": "Quita de la barra los botones de Vista de tareas, Cortana y Contactos. El buscador queda.",
  "Desanclar todas las apps del menu Inicio": "Deja el menú Inicio sin apps ancladas (para armarlo a tu gusto). Avanzado: tendrás que volver a anclar las que uses.",
  "Desactivar panel de Widgets": "Quita el botón de Widgets (noticias, clima) de la barra y lo bloquea. Ahorra memoria y procesos en segundo plano.",
  "Desactivar botón Chat / Teams en barra de tareas": "Quita el botón de Chat/Teams de la barra de tareas de Windows 11.",
  "Desactivar Copilot": "Quita el botón de Copilot y lo desactiva por política.",
  "Borrar accesos directos rotos (destino inexistente)": "Borra del escritorio y del menú Inicio los accesos directos que apuntan a programas que ya no existen.",
  "Deshabilitar permisos (excepto Cámara, Micrófono, Vídeos)": "Les quita a las apps el acceso a ubicación, contactos, calendario, archivos, Bluetooth y más. Cámara y micrófono quedan. Si una app deja de funcionar, usá Reactivar → Permisos.",
  "Deshabilitar Activación por Voz": "Las apps (como Cortana) dejan de escuchar una palabra de activación en segundo plano.",
  "Deshabilitar apps en segundo plano": "Las apps de la Store no corren cuando no las usás: menos RAM y CPU. Ojo: las de la Store (WhatsApp, Spotify…) pueden dejar de mostrar notificaciones.",
  "Deshabilitar notificaciones de apps": "Bloquea las notificaciones de las apps. Menos interrupciones mientras jugás, pero no vas a ver avisos de ninguna app.",
  "Deshabilitar servicios de Xbox": "Apaga los servicios de Xbox. Avanzado: rompe Game Pass para PC (inicio de sesión), las partidas guardadas en la nube y los controles/accesorios de Xbox. Solo si no usás nada de Xbox. Se revierte en Reactivar → Xbox / Game Pass.",
  "Deshabilitar Remote Registry": "Impide que otras PCs de la red lean o cambien tu registro. Más seguro; casi nadie lo necesita.",
  "Deshabilitar Print Spooler (si no usas impresora)": "Apaga el servicio de impresión. Avanzado: no vas a poder imprimir ni usar “Imprimir en PDF” hasta reactivarlo (Reactivar → Impresora).",
  "Deshabilitar Windows Defender (ADVERTENCIA: reduce proteccion)": "Apaga el antivirus de Windows. Peligroso: tu PC queda sin protección si no tenés otro antivirus. En Windows moderno la “Protección contra alteraciones” suele bloquearlo: la app te avisa si no se pudo.",
  "Menú contextual clásico (clic derecho de W10)": "Vuelve al menú de clic derecho completo de Windows 10, sin el “Mostrar más opciones”. Reinicia el Explorador.",
  "Mostrar extensiones de archivo": "Muestra la extensión (.exe, .pdf, .jpg…). Ayuda a detectar archivos peligrosos disfrazados (ej. “foto.jpg.exe”).",
  "Mostrar archivos y carpetas ocultos": "Muestra en el Explorador los archivos y carpetas ocultos (como AppData).",
  "“Finalizar tarea” con clic derecho en la barra": "Agrega “Finalizar tarea” al clic derecho de cada app en la barra: cerrás un juego colgado sin abrir el Administrador de tareas.",
  "Alinear barra de tareas a la izquierda": "Pone el botón Inicio y los íconos a la izquierda, como en Windows 10.",
  "Desactivar Consumer Features (sugerencias y anuncios)": "Evita que Windows instale solo apps “sugeridas” (Candy Crush y compañía) y muestre promociones.",
  "Quitar sugerencias/anuncios del menú Inicio": "Quita las apps recomendadas y los anuncios del menú Inicio.",
  "Quitar búsqueda de Bing del menú Inicio": "La búsqueda del Inicio solo busca en tu PC: más rápida y sin resultados web de Bing.",
  "Debloat de Microsoft Edge (quitar promos)": "Apaga en Edge el asistente de compras, la barra lateral y las recomendaciones. No desinstala Edge.",
  "Desactivar seguimiento de ubicación": "Apaga el servicio de ubicación de Windows. Las apps de mapas o clima no van a saber dónde estás.",
  "Desactivar Storage Sense": "Evita que Windows borre solo archivos temporales o de la Papelera. Útil si preferís limpiar a mano.",
  "Desactivar Wi-Fi Sense": "Evita que Windows comparta o se conecte solo a redes Wi-Fi sugeridas.",
  "Desactivar telemetría de PowerShell 7": "PowerShell 7 deja de enviar datos de uso a Microsoft. No afecta a Windows PowerShell.",
  "Desactivar hibernación (libera espacio)": "Borra el archivo de hibernación (varios GB). Avanzado: también desactiva el “inicio rápido” y la opción Hibernar.",
  "Desactivar IPv6": "Desactiva IPv6 en tus adaptadores de red. Avanzado: algunos proveedores y juegos lo usan; si perdés conexión, revertilo.",
  "Desactivar reinicio automático tras actualizar": "Windows Update no reinicia la PC solo si hay alguien con la sesión abierta (no te corta una partida).",
  "Pantalla azul (BSOD) con detalles técnicos": "Si aparece una pantalla azul, muestra el código y el driver que la causó: ayuda a encontrar el problema.",
  "Mensajes detallados al iniciar sesión": "Muestra qué está haciendo Windows al iniciar y apagar (útil si tarda mucho).",
  "Activar NumLock al iniciar Windows": "El teclado numérico queda activado desde la pantalla de inicio de sesión.",
  "Desactivar Sticky Keys": "Evita el aviso de “Teclas especiales” al apretar Shift 5 veces (muy molesto en juegos).",
  "Mostrar segundos en el reloj de la barra": "El reloj de la barra de tareas muestra también los segundos.",
  "Hora del sistema en UTC (dual-boot con Linux)": "Hace que Windows interprete el reloj de la PC en UTC, como Linux. Avanzado: solo si usás Linux en la misma PC y la hora se desfasa.",
  "Desactivar servicio HomeGroup": "Apaga los servicios de Grupo Hogar (función vieja de redes que Windows 10/11 ya no usa).",
};
