// Descripciones cortas de qué hace cada tweak (para los tooltips)
export const TWEAK_DESC: Record<string, string> = {
  "Plan de energía: Máximo rendimiento": "Activa el plan de energía de alto rendimiento: la CPU no baja su frecuencia para ahorrar, ideal para juegos.",
  "Habilitar Game Mode de Windows": "Prioriza recursos para el juego en primer plano y reduce tareas de fondo mientras jugás.",
  "Deshabilitar Xbox Game Bar y DVR": "Apaga la grabación en segundo plano del Game Bar, que consume CPU/GPU y puede causar tirones.",
  "Hardware Accelerated GPU Scheduling (HAGS)": "Deja que la GPU gestione su propia memoria/planificación, bajando la latencia en tarjetas modernas.",
  "Prioridad CPU máxima para juegos": "Sube la prioridad de CPU/GPU para tareas de juego en el registro de Windows.",
  "Deshabilitar Full-Screen Optimization (FSO)": "Fuerza pantalla completa exclusiva real, reduciendo input lag en algunos juegos.",
  "Deshabilitar aceleración del mouse": "Hace que el movimiento del mouse sea 1:1 (sin aceleración), clave para apuntar en shooters.",
  "Timer Resolution — 1ms (reduce micro-stutters)": "Fuerza el temporizador del sistema a 1ms para suavizar micro-tirones. Avanzado: crea una tarea al inicio.",
  "Core Parking OFF — todos los núcleos activos": "Evita que Windows 'aparque' núcleos de la CPU, manteniéndolos todos activos. Avanzado.",
  "Deshabilitar algoritmo de Nagle (ping más bajo)": "Desactiva el agrupado de paquetes TCP, bajando la latencia en juegos online.",
  "Deshabilitar Teredo": "Apaga el túnel IPv6 Teredo, que puede causar problemas de conexión en algunos juegos.",
  "Optimizar TCP": "Ajusta parámetros TCP (autotuning, RSS) para mejor rendimiento de red.",
  "Deshabilitar Large Send Offload (LSO)": "Desactiva LSO, que en muchas placas de red causa picos de latencia.",
  "Reservar 0% de ancho de banda para QoS": "Libera el 20% de ancho de banda que Windows reserva por defecto para QoS. Avanzado.",
  "Plan de energía Ultimate Performance": "Activa el plan oculto 'Ultimate Performance', aún más agresivo que Alto rendimiento.",
  "MSI mode en la GPU (menos latencia)": "Activa interrupciones por mensaje (MSI) en la GPU para reducir latencia. Avanzado: requiere reiniciar.",
  "Bloquear telemetría (archivo hosts)": "Agrega los dominios de telemetría de Microsoft al archivo hosts para bloquearlos. Avanzado.",
  "Desactivar Recall (captura de IA)": "Desactiva Recall de Windows 11, que toma capturas periódicas de tu pantalla.",
  "Quitar OneDrive por completo": "Desinstala OneDrive y borra su carpeta. Avanzado: hacelo solo si no lo usás.",
  "Deshabilitar telemetría de Windows": "Reduce al mínimo la recolección de datos de diagnóstico de Windows.",
  "Deshabilitar ID publicitario y Cortana": "Apaga el identificador de publicidad y la asistente Cortana.",
  "Desactivar animaciones y efectos visuales": "Quita animaciones de ventanas y menús para una respuesta más rápida.",
  "Deshabilitar transparencia de Windows": "Apaga los efectos de transparencia, ahorrando algo de GPU.",
  "Activar Modo Oscuro (apps y sistema)": "Pone Windows y las apps en tema oscuro.",
  "Deshabilitar SysMain / Superfetch": "Apaga el servicio de precarga, útil sobre todo en equipos con SSD.",
  "Deshabilitar Windows Search (indexado)": "Apaga la indexación de búsqueda, que consume disco. Avanzado: la búsqueda se vuelve más lenta.",
};
